### PR TITLE
Close #831 Fix Typo in GPL/LGPL header

### LINKED ISSUE #831: Error in the libPMacc license header
In many (maybe all) of the libPMacc sources there is a mistake in the license header:
...`it under the terms of of either the GNU General Public License or`...
The double `of of` should be combined to a single `of`.
This change would touch nearly all of the existing files.

### PR DESCRIPTION
**Pull request by ax3l**
Close #831 via one-liner & [generic commit](https://github.com/ComputationalRadiationPhysics/picongpu/issues/755).

```bash
grep -iR "of of" . | awk -F':' '{print $1}' | xargs sed -i "s/of of/of/g"
GIT_AUTHOR_NAME="Tools" GIT_AUTHOR_EMAIL="picongpu@hzdr.de" git commit -a -m "Close #831 Fix Typo in GPL/LGPL header"
```

### CODE REVIEW

**Comment by psychocoderHPC** [comment]
Can you please also change the license template in: https://github.com/ComputationalRadiationPhysics/picongpu/blob/master/src/tools/bin/addLicense#L67

**Comment by ax3l** [comment]
I did that already :)

https://patch-diff.githubusercontent.com/raw/ComputationalRadiationPhysics/picongpu/pull/834.patch

**Comment by psychocoderHPC** [comment]
Ahh sry, I haven't seen the github massage that not all files were listed.

**Comment by ax3l** [comment]
Yes, that happened due to the tremendous number of files that were affected ^^

**Pull request merged**
