### PR TITLE
SliceField Plugin: Option .frequency to .period

### PR DESCRIPTION
**Pull request by PrometheusPi**
This pull request changes for all sliceField plugins the `.frequency` call to `.period` (as used in all other plugins). This makes the interface of the plugin more coherent.

Thanks @steindev for pointing out this issue *offline*. 

### To Do

- [x] please also adjust the private vars such as `notifyFrequency` accordingly
- [x] please also adjust the `docs/TBG_macros.cfg` example
- [x] please also adjust the [wiki article](https://github.com/ComputationalRadiationPhysics/picongpu/wiki/Plugin%3A-SliceFieldPrinter)

### CODE REVIEW

**Comment by PrometheusPi** [comment]
@ax3l regarding `docs/TBG_macros.cfg`: There is nothing on this plugin there yet. Should I add it - or skip a usage example?

**Comment by ax3l** [comment]
oh yes, let us add it :)

**Comment by PrometheusPi** [comment]
@ax3l But the variable name `notifyFrequency` is used by all other variables as well. What do you mean with: *"please also adjust the private vars such as `notifyFrequency` accordingly"*

**Comment by ax3l** [comment]
> But the variable name notifyFrequency is used by all other variables as well

yes, please refactor the name of this plugin variable throughout the complete plugin by renaming it accordingly. A name we commonly use is `notifyPeriod`.

**Comment by PrometheusPi** [comment]
@ax3l finished
I changes the variable name in the entire plugin.
There are some more plugins with the old naming. I will open another pull request to fix those as well. (perhaps tomorrow)

**Pull request merged**
