### PR TITLE
fix typo Axl-> Axel and Phot->Photon

### PR DESCRIPTION
**Pull request by PrometheusPi**
This pull request fixes to typos in the selection of possible pushers.

This avoids selecting a wrongly spelled and thus non-existing pusher.

### CODE REVIEW

**Comment by psychocoderHPC** [comment]
We should rename all our pusher e.g `particlePusherPhot` to `Photon`. The name pusher and particle are already given by the namespace

**Comment by ax3l** [comment]
`dev` did not yet move the
`src/picongpu/include/particles/pusher/{particlePusherPhot.hpp → particlePusherPhoton.hpp}` file to make this consistent.

**Comment by ax3l** [comment]
(will do)

**Comment by PrometheusPi** [comment]
@Axel - as discussed with @psychocoderHPC (second comment) the idea was to rename all pusher files consistently from `particlePusherXYZ.hpp` to `XYZ.hpp` and to do this in one pull request together.

**Comment by ax3l** [comment]
hm, confusing not to do this timely. the documentation was already changed 2 weeks ago, so at least its consistent now again.

**Pull request merged**
