### PR TITLE
devServer install and profile for a100/a30

### PR DESCRIPTION
**Pull request by BrianMarre**
new profile and spack install script for nvidi a100/a30 gpus

### CODE REVIEW

**Comment by PrometheusPi** [comment]
@BrianMarre please provide a description

**Comment by BrianMarre** [comment]
@PrometheusPi done

**Comment by psychocoderHPC** [comment]
We do not have a A100 GPU only a A30, the name should reflect this.

**Comment by BrianMarre** [comment]
@psychocoderHPC @PrometheusPi reviewer suggestions are included

**Review by PrometheusPi — APPROVED** [review]

**Pull request merged**
