### PR TITLE
Wrong border with current background field

### LINKED ISSUE #943: BG Field: Current Added to Guard
The BG fields for at least `FieldJ` is added to the `GUARD` region (but should only apply for the `BORDER` + `CORE` region since the current is communicated afterward).

Needs also to be checked for `FieldE` and `FieldB`.

### PR DESCRIPTION
**Pull request by psychocoderHPC**
fix #943

If field background is used than the border regions will be wrong.
The field background current is operationg on the local domain regions
`CORE + BORDER + GUARD`. The current is than scattered to the neighboring GPUs
and will create wrong border regions.

- operate background field current only on the region `CORE + BORDER`
- fix `cellwiseOperation` - index passed to the user functor was only correct if `CORE+GUARD + BORDER` was manipulated

With this fix current smoothing is still possible. **Attention** FieldJ is not part of the checkpointing #2325

~~do not merge, there is a wrong index calculation in `cellwiseOperation.hpp`~~

CC-ing: @steindev

### CODE REVIEW

**Comment by ax3l** [comment]
looks good, we just need a RT validation and maybe a check with current smoothing on

**Comment by psychocoderHPC** [comment]
@steindev Could you please post the plot from the broken background field J to this PR.

**Comment by steindev** [comment]
The picture shows the hdf5 output of `fields/J` where the current density in the simulation is defined via `FieldBackgroundJ` which is set to `-1` everywhere. The simulation used 8 GPUs, with 2 per direction.

The `FieldBackgroundJ` is added in the region between two GPUs resulting in a wrong current density.

background-current_error

**Comment by steindev** [comment]
Repeated test with applied fix: works!

background-current_error_fix

**Comment by steindev** [comment]
Update: Works as expected, ALMOST. Now I ran a test with a straight conductor of one cell width. The conductor is (supposed to be) located at positions x=z=96 for all y. But it is not.

In the following picture, the current should be located in the top right corner of the picture. Btw. this is just a part of my simulation volume. In total it is 192x192x192.

background-current_error_fix_error

**Comment by PrometheusPi** [comment]
@steindev Did @psychocoderHPC fix solves your issue?

**Comment by steindev** [comment]
he current is now at the correct position. Furthermore, it fixes a bug which caused the background current to be added with every time step in the left border of the simulation volume. This caused an electric field pile up within the absorber.

background-current_error_fix_error_fix

**Comment by PrometheusPi** [comment]
@steindev I am confused by the left plot. If the current is equal along y, why does it reduce towards the boarder?

**Comment by steindev** [comment]
Cells 0-32 are the absorber and the left plot shows the electric field generated by the current. Therefore, a reduction is expected.

**Comment by ax3l** [comment]
thank you both, great catch! :)

**Pull request merged**
