### PR TITLE
fix processing of outgoing particles by multi plugins

### LINKED ISSUE #3618: particleCalorimeter plugin not processing outgoing particles, missing onParticleLeave in multi::Master
The Interface for multi plugins doesn't handle outgoing particles correctly. If a multi plugin defines `onParticleLeave` it will not be called, instead the empty implementation from the `IPlugin` class will be used. 
Right now only `particleCalorimeter`defines `onParticleLeave`but since  #2563 that plugin is a multi plugin and the outgoing particles are __not__ processed. 

It's a quick fix. I will open a PR.

### PR DESCRIPTION
**Pull request by pordyna**
aims to fix  #3618

### CODE REVIEW

**Review by psychocoderHPC — APPROVED** [review]

**Comment by pordyna** [comment]
It looks like the compile error 
> g++-10: fatal error: Killed signal terminated program cc1plus

 is somehow CI related. @psychocoderHPC Could you restart the two failing tests?

**Comment by sbastrakov** [comment]
It can be that the compiler runs out of memory. But even if so, restanting may help it pass through

**Comment by psychocoderHPC** [comment]
I restarted the CI again.

**Comment by psychocoderHPC** [comment]
I restarted the CI but somehow the CI not pushed back the status. I will merge this PR.

**Review by psychocoderHPC — APPROVED** [review]

**Pull request merged**
