### PR TITLE
improve graphics of numerical heating tool

### PR DESCRIPTION
**Pull request by PrometheusPi**
This pull requests improves the graphics of the `plotNumericalHeating` tool as suggested by @psychocoderHPC .

The new look can be seen here:
numheating_newgraphics

Compare this to [the following plot](https://github.com/ComputationalRadiationPhysics/picongpu/pull/730#issuecomment-77185517) where the small scale oscillation of `branch` is not visible due to the dashed line.

### CODE REVIEW

**Comment by ax3l** [comment]
sweet. it would be even better if the colored area would change the color with the sign of the delta, but I can merge it already if you like.

**Comment by PrometheusPi** [comment]
@ax3l I already thought about it, but a green background for less numerical heating implies an improvement which is not always true (see some of the cases of @psychocoderHPC ). I would stay with red, but perhaps two kinds of red background. What do you think?

**Comment by ax3l** [comment]
what about red and beige?

**Comment by ax3l** [comment]
@PrometheusPi just waiting for that change

**Comment by PrometheusPi** [comment]
Now, we differentiate between whether dev or branch are closer to the inital energy.

The red color is darker, if `branch` is farther awy than `dev`.
- `dev` > start **and**  `dev` > `branch` *light red* 
- `dev` > start **and**  `dev` < `branch` *dark red* 
- `dev` < start **and**  `dev` < `branch` *light red* 
- `dev` < start **and**  `dev` > `branch` *dark red* 

numheating_newgraphics2

**Comment by ax3l** [comment]
thanks!
your choice is pretty hard to see but if you like that it is fine with me.

**Comment by PrometheusPi** [comment]
Yes, I like that - any deviation should cause concern. That's why both should be pretty much the same red.

**Comment by ax3l** [comment]
yes but the colors are impossible to tell apart for most people, especially on crappy LCD displays. e.g., red / orange is also an option.

**Comment by psychocoderHPC** [comment]
Yes it's hard to see the difference. 
I know that yellow and red is a awful combination with the blue and green line but might be it give more contrast.

**Comment by PrometheusPi** [comment]
numheating_newgraphics3

**Comment by PrometheusPi** [comment]
after discussing with @psychocoderHPC 

numheating_newgraphics4

**Comment by psychocoderHPC** [comment]
The last plot is my favorite also it is very colorfull

**Comment by ax3l** [comment]
Agreed, the red/sandish one is pure sugar. Like it, too.

**Comment by ax3l** [comment]
well done @PrometheusPi, thank you for the updates! :+1:

**Pull request merged**
