### PR TITLE
Closes #1154: Introduce CONSTEXPR macro

### LINKED ISSUE #1154: Static Const Float Values in C++11
According to the C++ standard the in-class definition of `static const float* = xxx` is not allowed: http://stackoverflow.com/questions/2454019/why-arent-static-const-floats-allowed  
For some reason this works currently for C++98.

However this breaks when compiling with C++11

> error: ‘constexpr’ needed for in-class initialization of static data member ‘const float_X <name>’ of non-integral type [-fpermissive]
> ...
> note: ‘picongpu::SI::SPEED_OF_LIGHT_SI’ was not declared ‘constexpr’
> ...
> error: the value of ‘picongpu::SI::CELL_HEIGHT_SI’ is not usable in a constant expression

### PR DESCRIPTION
**Pull request by Flamefire**
This introduces a new define `CONSTEXPR` which should be used instead of `const` for all in-class `static` variables. It *must* be used for declaring `static const float foo = 42.1337` as this is an error for C++11 and was probably never allowed. (See #1154)

It does not hurt to use this for all `static const`s used and may even increase performance in C++11 mode.

However it does not try to emulate `constexpr` in any way for C++98. So functions cannot be decorated with this (e.g. `CONSTEXPR inc(int x){ return x+1; }` which would be possible in C++11 but is **NOT** allowed for C++98.

### CODE REVIEW

**Comment by ax3l** [comment]
thank you for the update.

would you mind refactoring it a tiny bit?

I would like to see the following implementation:
`PMacc` implements a helper macro called `PMACC_CONSTEXPR` in [`src/libPMacc/include/types.h`](https://github.com/ComputationalRadiationPhysics/picongpu/blob/2e56da6ae0eb58027495a072aa683b67d9446389/src/libPMacc/include/types.h#L63) which is, as you already did, defined to `const` or `constexpr` depending by default on the macro `BOOST_NO_CXX11_CONSTEXPR` from boost.

By that, the complete configuration is a feature provided by PMacc and does not clutter CMakeLists.txt. Also, it can still be overwritten if you implement it like this (inspired by [boost configs](https://github.com/boostorg/config/blob/89fd23ad0a4e7786e57c2ac9e4ffcc1015020477/include/boost/config/suffix.hpp#L606-L619) that we use the same way [in our examples](https://github.com/ComputationalRadiationPhysics/picongpu/blob/2e56da6ae0eb58027495a072aa683b67d9446389/examples/LaserWakefield/include/simulation_defines/param/componentsConfig.param#L54-L56)) ([PP style](https://github.com/ComputationalRadiationPhysics/picongpu/wiki/Coding-Guide-Lines#2-pre-compiler)):

```c++
/* probably needs this include: */
#include <boost/config.hpp>

// [...]

/** C++11 Compatibility: PMACC_CONSTEXPR
 *
 * Should be used instead of 'const', e.g., for 'static const' members in classes.
 * This evaluates to 'constexpr' for C++11 allowing compilation of, e.g.,
 *   static const(expr) float foo = 42.1337;
 * It MUST NOT be used to mark 'constexpr' functions as this
 * is not supported in C++98.
 */
#ifndef PMACC_CONSTEXPR
#    ifdef BOOST_NO_CXX11_CONSTEXPR
#        define PMACC_CONSTEXPR const
#    else
#        define PMACC_CONSTEXPR constexpr
#    endif
#endif
```

**Comment by ax3l** [comment]
alternatively, we can check the `__cplusplus` macro or define a
```cmake
add_definitions(-DPMACC_CXX_STANDARD=${CMAKE_CXX_STANDARD})
```

so additional macros can depend on it in case we need them.

**Comment by Flamefire** [comment]
I'd rather use the __cplusplus macro as commonly used in the stl. If we are to use Boost we can use the boost defines:

    #if defined(BOOST_NO_CXX11_CONSTEXPR)
    #define BOOST_CONSTEXPR
    #define BOOST_CONSTEXPR_OR_CONST const
    #else
    #define BOOST_CONSTEXPR constexpr
    #define BOOST_CONSTEXPR_OR_CONST constexpr
    #endif

    #define BOOST_STATIC_CONSTEXPR  static BOOST_CONSTEXPR_OR_CONST

I actually like them, so if we don't use these as they are I'd define PMACC equivalents for them.

**Comment by ax3l** [comment]
also be careful what you need from cmake, some target flags were just added in [cmake 3.1.0](https://cmake.org/cmake/help/v3.1/release/3.1.0.html)

**Comment by Flamefire** [comment]
About cmake versions: This is why I added the unified C++11 check in the previous PR. Although this flag may not be supported by CMake we can be sure it is correctly set or unset.

**Comment by ax3l** [comment]
using it is not a problem, just make sure the cmake requirement is increased in case it needs to.

**Comment by Flamefire** [comment]
I don't rely on any CMake version in this PR.

**Comment by ax3l** [comment]
defining a
```c++
/* probably needs this include: */
#include <boost/config.hpp>

// [...]

/** C++11 Compatibility: PMACC_CONSTEXPR
 *
 * Should be used instead of 'const', e.g., for 'static const' members in classes.
 * This evaluates to 'constexpr' for C++11 allowing compilation of, e.g.,
 *   static const(expr) float foo = 42.1337;
 * It MUST NOT be used to mark 'constexpr' functions as this
 * is not supported in C++98.
 */
#ifndef PMACC_CONST
#    define PMACC_CONST BOOST_CONSTEXPR_OR_CONST
#endif
```

would be totally fine for me, too (I like keeping the name a bit short because it appears in parameter files).

**Comment by ax3l** [comment]
updated

**Comment by Flamefire** [comment]
Hmm... Seems the boost macros or just for internal use. I can't find any docu for them.
So I would rather duplicate that renaming the `BOOST_` prefix to `PMACC_`.
Keeping the name short was my intention for not using the prefix. However I'd like to have 2 macros for `CONSTEXPR` and `CONSTEXPR_OR_CONST` as both have their use-cases (see #1158)
I also find the `BOOST_STATIC_CONSTEXPR` a nice way to ommit the `_OR_CONST` suffix.

**Comment by ax3l** [comment]
> I don't rely on any CMake version in this PR.

I was just asking because I was not sure when CMake introduced the `CMAKE_CXX_STANDARD` variable? 3.0+?

**Comment by ax3l** [comment]
@Flamefire I think it is the best if we define just the two use cases we need:
here we need a `BOOST_STATIC_CONSTEXPR` equivalent for members and #1158 just needs a `BOOST_CONSTEXPR` equivalent (empty or set).

**Comment by Flamefire** [comment]
I would propose: `PMACC_STATIC_CONSTEXPR`, `PMACC_CONSTEXPR` and `PMACC_CONSTEXPR_FUNC`(=constexpr or empty)

> I was just asking because I was not sure when CMake introduced the CMAKE_CXX_STANDARD variable? 3.0+?

As mentioned:
>This is why I added the unified C++11 check in the previous PR. Although this flag may not be supported by CMake we can be sure it is correctly set or unset.

This variable is set before. CMake 3.0x understands that, but I don't care here if CMake understands that. I added a kind of "legacy" support for that variable so: `CMAKE_CXX_STANDARD==11 <=> NVCC_FLAGS contain -std=c++11` (read the `<=>` as the logic sign 'exactly when')

**Comment by ax3l** [comment]
all right, I am with you but think
  - `PMACC_STATIC_CONSTEXPR` (`static const` or `static constexpr`; for members)
  - `PMACC_CONSTEXPR` (set to `constexpr` or empty; for function usage)

**Comment by Flamefire** [comment]
That does not work for all those namespace consts we have. We need a `CONSTEXPR_OR_CONST` define for those.

**Comment by ax3l** [comment]
> Hmm... Seems the boost macros or just for internal use. I can't find any docu for them.

here is the [boost config documentation](http://www.boost.org/doc/libs/1_59_0/libs/config/doc/html/index.html) you were looking for

**Comment by Flamefire** [comment]
Is there any reason not to use the boost defines? They are listed there since 1.52 at least: http://www.boost.org/doc/libs/1_52_0/libs/config/doc/html/boost_config/boost_macro_reference.html#boost_config.boost_macro_reference.boost_helper_macros

**Comment by ax3l** [comment]
I was thinking that, too.

one thing is: it allows us to change them. but on the other hand: a c++98 compiled boost will not work with c++11 and vice versa.

so using them directly should be fine I guess.

**Comment by Flamefire** [comment]
A C++98 compiled boost of at least version 1.57 will work with C++11 compiled PMacc and vice versa. I'm not aware that the ABI changed there. Only reason why < 1.57 is not working is due to a know defect with scoped enum emulation in boost::filesystem: https://svn.boost.org/trac/boost/ticket/6779

**Comment by ax3l** [comment]
Ah looks [like you already found](https://github.com/ComputationalRadiationPhysics/picongpu/issues/1147#issuecomment-144431856) an [ABI incompatebility](https://svn.boost.org/trac/boost/ticket/6779) that is reported in `boost::filesystem` (and we use that).

**Comment by ax3l** [comment]
so for us its: yes, boost should better be compiled with the same language standard as the following PMacc/PIConGPU and due to that we should be totally fine using the boost macros directly.

**Comment by Flamefire** [comment]
I just wanted to point out, that no problems are to be expected, when a recent boost version (>= 1.57) is used even for mixed standards.

**Comment by ax3l** [comment]
that is really cool, but a bit too recent for our supported boost range.

**Comment by ax3l** [comment]
ok so I think we know how to continue, feel free drop me a line when you updated the PR.

**Comment by Flamefire** [comment]
I tried to add a work-around as all we need would be a redirection/proxy for that one function in case one is compiling with C++11 but I failed. See the corresponding SO: http://stackoverflow.com/questions/32870467/access-to-different-struct-with-same-name

**Comment by Flamefire** [comment]
WIP: DO NOT MERGE

**Comment by Flamefire** [comment]
Current status for all PIConGPU examples with C++11, CUDA 7, boost 1.59:

     ...........,_
     ........../.(|
     ..........\..\ 
     ........___\..\,. ~~~~~~
     .......(__)_)...\ 
     ......(__)__)|...|
     ......(__)__)|.__|
     .......(__)__)___/~~~~~~

**Comment by ax3l** [comment]
just for the record, can you link the reference for that statement?

> I just wanted to point out, that no problems are to be expected, when a recent boost version (>= 1.57) is used even for mixed standards.

**Comment by Flamefire** [comment]
https://svn.boost.org/trac/boost/ticket/6779 says the problem with boost::filesystem is fixed in 1.57

**Comment by ax3l** [comment]
yes saw the successful link, just needed a quot-able reference for the future.

**Comment by bussmann** [comment]
u r awesome.
next: C++ 14

**Comment by Flamefire** [comment]
C++14 does not add any language features that I'm aware of. Just some nice shortcuts using the template using feature from C++11 :)

**Comment by bussmann** [comment]
I know. Just wanted to point out that PIConGPU is now C++ 14 compliant.

**Comment by ax3l** [comment]
without being pedantic, but your `BOOST_STATIC_CONSTEXPR` replacements all added a superfluous space.

**Comment by Flamefire** [comment]
Thanks. Fixed that.
Before this is merged: I found a lot of `static const` variables in the code. It is probably the best, to replace them as well. Most of the stuff can be done with Search&Replace with a few fine tunings. Components include MallocMC, PMacc, picongpu, cuSTL

**Comment by ax3l** [comment]
to use the boost macros safely, we should add the [according include](http://www.boost.org/doc/libs/1_59_0/libs/config/doc/html/index.html#boost_config.configuring_boost_for_your_platform.the__boost_config_hpp__header)
```c++
#include <boost/config.hpp>
```

in a central file such as `libPMacc/include/types.h` so it is already known for `.param` files in any case.
(just saw `types.h` already includes commonly used boost headers, so actually we can also skip it but this makes it more explicit in case `fs` or some other includes move to a cleaner place...)

**Comment by ax3l** [comment]
@Flamefire wait, let us merge the changes to `param` files and examples first.

you can update the rest in a second PR pls!

Please provide a PR for [mallocMC](https://github.com/ComputationalRadiationPhysics/mallocMC) in it's upstream repo.

**Comment by Flamefire** [comment]
Added include

**Comment by ax3l** [comment]
ok, looks good to me :sparkles:

**Comment by Flamefire** [comment]
Added a PR for the `static const` values. I did not look for any other consts as I don't think it will be worth the work (manual search required) but `static consts` can be used from "user code" and therefore should provide support for C++11.
I also did not add any PR for mallocMC. Users will probably not use any consts from mallocMC so the benefit will be low to non-existant.

**Pull request merged**
