### PR TITLE
reduce visualization gpu memory footprint

### PR DESCRIPTION
**Pull request by psychocoderHPC**
allocate image memory only if gpu participate on the visualization

related to #1279

**Tests:**

- [x] 3D LWFA with sliding window (checked png images)

### CODE REVIEW

**Comment by erikzenker** [comment]
The initialization of img has been moved to the [init()](https://github.com/psychocoderHPC/picongpu/blob/topic-reducePngPluginGpuMemoryFootprint/src/picongpu/include/plugins/output/images/Visualisation.hpp#L609-L637). What happends if the Visualisation class is used without calling init() ? I guess segmentation faults, since img was not initialized correctly. Should we add some bool isInitialized ?

**Comment by ax3l** [comment]
it's not directly a plugin, but since it implements [ILightweightPlugin](https://github.com/ComputationalRadiationPhysics/picongpu/wiki/Develop-Plugins) instead of `init` the methods `pluginLoad`/`pluginUnload` would be a way to implement that more transparent.

(Be aware that some kind of convention needs to be done since constructors and destructors are often too early/late when dealing with GPU memory. Nevertheless, in this case `Visualisation` is directly used in `LiveViewPlugin` and `PngPlugin` which might be in control of it's construction in their `plugin(Un)load` methods.)

**Comment by erikzenker** [comment]
> Nevertheless, in this case Visualisation is directly used in LiveViewPlugin and PngPlugin which might be in control of it's construction in their plugin(Un)load methods.)

If it can be used wrong it will be used.

**Comment by ax3l** [comment]
just have a short talk to @psychocoderHPC, maybe you find a saver way

**Pull request merged**
