### PR TITLE
rename "counterParticles" to "numParticles"

### PR DESCRIPTION
**Pull request by finnolec**
I refactored `counterParticles` as suggested by @ax3l and @sbastrakov in #2642.

### CODE REVIEW

**Comment by sbastrakov** [comment]
@finnolec thx for closing this long-standing issue!

**Comment by finnolec** [comment]
@PrometheusPi I can do that, but I don't really think that my changes here are substantial enough to say that I actually did something :smile:

**Comment by PrometheusPi** [comment]
@finnolec You decide - if you think your commit is not substantial enough to add your name, I am fine with that. I just asked, so that I do not merge beforehand.

**Comment by finnolec** [comment]
I don't mind if you just merge it :)

**Pull request merged**
