### PR TITLE
Fix laser bug in case focus position is at the init plane

### PR DESCRIPTION
**Pull request by hightower8083**
this PR addresses #2921

### CODE REVIEW

**Comment by hightower8083** [comment]
I'm a bit lame with `git` when in comes beyond `commit`, `push` and `pull`.. 
I thick, here I've managed to squash for the last two commits. Let me know if it's OK with you.

**Comment by sbastrakov** [comment]
@hightower8083 looks like the last two commits have been squashed fine. I am not sure why do you need the first commit. In case you actually do not need it, could do rebase again and skip it.

**Comment by psychocoderHPC** [comment]
@hightower8083  I will squash the PR for you

**Comment by hightower8083** [comment]
@psychocoderHPC Thanx, Rene, busy parenting weekend -- no time even to tune a tiny PR =)
@sbastrakov yep, I noticed where I've made a mistake (should have changed both commits to _squash_ instead of _pick_). Will know it better next time ;-)

**Pull request merged**
