### PR TITLE
crusher hipcc profile

### PR DESCRIPTION
**Pull request by psychocoderHPC**
- rename existing profile in `batch_craycc_picongpu.profile.example`
  - add warning which recomended to use hipcc instead of CRAY CC
- add hipcc profile `batch_hippcc.profile.example`

### CODE REVIEW

**Review by sbastrakov — COMMENTED** [review]
Neither of the Crusher profiles are now cited at readthedocs, could you add those to [here](https://github.com/ComputationalRadiationPhysics/picongpu/blob/dev/docs/source/install/profile.rst)?

**Comment by psychocoderHPC** [comment]
> Neither of the Crusher profiles are now cited at readthedocs, could you add those to [here](https://github.com/ComputationalRadiationPhysics/picongpu/blob/dev/docs/source/install/profile.rst)?

Thanks, I added both profiles to the documentation

**Review by PrometheusPi — APPROVED** [review]
lgtm

**Comment by PrometheusPi** [comment]
There was still an error in this pull request - please see @steindev fix in #3976 for detail.

**Pull request merged**
