### PR TITLE
remove libmxml from library dependency graph

### PR DESCRIPTION
**Pull request by PrometheusPi**
This pull request is a followup to #1556 and #1557. It removes the `libmxml` dependency of adios from the library dependency graph.

### CODE REVIEW

**Comment by ax3l** [comment]
thanks!
but now the png it looks ugly/chaotic.

**Comment by PrometheusPi** [comment]
Yes, but that's what the hypnos version of `Graphviz` produces. The other options looks even more uglier.

**Comment by ax3l** [comment]
last time I added the optional dependency hdf5->adios by hand to clean it a bit up.

**Comment by ax3l** [comment]
P.S.: adios also depends on zlib

**Comment by PrometheusPi** [comment]
Is this not covered by the dependency on mpi (which depends on zlib)?

**Comment by ax3l** [comment]
> mpi (which depends on zlib)?

it does not in our file

**Comment by PrometheusPi** [comment]
@ax3l Sorry my fault, I meant hdf5-parallel.

**Comment by ax3l** [comment]
Ok, but it's still not included in the adios transports. Pls add the link :)

**Comment by PrometheusPi** [comment]
@ax3l I added the zlib dependency.

**Comment by ax3l** [comment]
pls use the attached image instead.
librarydependencies

**Comment by PrometheusPi** [comment]
@ax3l done

**Pull request merged**
