### PR TITLE
add expressions `DoNothing` and `SetToNull`

### PR DESCRIPTION
**Pull request by psychocoderHPC**
- add folder for expressions
- add expression
  - `DoNothing`
  - `SetToNull`

### CODE REVIEW

**Comment by BenjaminW3** [comment]
What is the use case of those expressions?
Is there a specification what exactly an ```expression``` is?
I think a function object with the same functionality would be easier to understand and use in most cases. If it is not to ease the optimization work for the compiler I do not see a advantage of a ```static perform``` method over an ```operator()```.

**Comment by psychocoderHPC** [comment]
- one example for usage: manipulate structs/classes that the default constructor can be empty in special situations
- IMO a expression is a rule how to do something (https://en.wikipedia.org/wiki/Expression_templates)
  - might be that we already had some expressions in PMacc but named it wrong and put it in `traits` but `traits != expression`

**Comment by psychocoderHPC** [comment]
Should I change `static perform()` to `operator()()`.
The only think what is not so nice while using `operator()` is that we must create a instance to use the operator.

**Comment by BenjaminW3** [comment]
I am unsure about this. Maybe renaming perform to eval is enough.

**Comment by psychocoderHPC** [comment]
OK I will change it to `eval`.

**Comment by psychocoderHPC** [comment]
I switched to `operator()()`. The reason is that a operator is more generic because we can use `boost::result_of()` (in C++98) and `std::result_of()` (in C++11)

**Pull request merged**
