### PR TITLE
Add Border-Mapping

### PR DESCRIPTION
**Pull request by Flamefire**
This adds a new mapper which maps to the full border on one side. The result is similar to using the exchange mapper on the guard region and adding an extra offset to get to the border. So for example a direction of LEFT will get the border of LEFT + TOPLEFT + BOTTOMLEFT (in 2D)

This can be used for spawning particles/laser/... from one specific side.

Some points that are different to other mappers:

- ~~Does not inherit from BaseClass but defines one values. Reasoning: Smaller structure, no redundant computation after construction~~
- ~~Direction is compile-time template parameter. Reasoning: Mostly the direction is fixed at compile-time, so this may make the initialisation basically constant. Also direction could be checked at compile-time~~ (currently run-time check at ctor is implemented)
- AreaType = BORDER member. Reasoning: Some kernels may enforce that they are only run on border by using static_asserts on this member

### CODE REVIEW

**Comment by psychocoderHPC** [comment]
Is it possible to move the direction to a runtime parameter. A typical case how it is used is [here](https://github.com/ComputationalRadiationPhysics/picongpu/blob/release-0.1.1/src/picongpu/include/fields/FieldManipulator.hpp)

**Comment by Flamefire** [comment]
Yes it is possible. But I wanted to keep it as small and fast as possible. I can also add a factory function with a switch to create an instance from a runtime value as there are only 9 cases.

**Comment by psychocoderHPC** [comment]
This are 6 areas if it is 3D and only call able for planes. But a switch case is not very nice style and for this small optimization a premature optimization.

**Comment by Flamefire** [comment]
Right, there are only 6. I actually can't see anything wrong with a switch, but ok. Runtime parameter then.

**Comment by psychocoderHPC** [comment]
Big thanks, this mapper is very important for use to simplify  some of my ugly kernels^^

**Comment by Flamefire** [comment]
Ok done. I don't think we need to keep the direction after the ctor. If this is required I'll re-add the getter-function.

**Comment by Flamefire** [comment]
I now also derive from the base class. This mapper is now following the same scheme as the other mappers (one e.g. often needs access to the number of guard cells)

**Comment by psychocoderHPC** [comment]
After my vacation a looked over the code with a fresh view and saw that we can easily skip the double implementations for each dimension.

```C++
HINLINE DimDataSpace getGridDim() const
{
    DataSpace<DIM2> result(base.getGridSuperCells() - 2 * base.getGuardingSuperCells());

   const DataSpace<DIM> directions = Mask::getRelativeDirections<DIM >(m_direction);

   for(uint32_t d=0; d<DIM; ++d)
   {
       if (m_directions[d] != 0)
            result[d] = this->getBorderSuperCells();
   }
   return result;
}
HDINLINE DimDataSpace getSuperCellIndex(const DimDataSpace& realSuperCellIdx) const
{
  DataSpace<DIM> result;
  DataSpace<DIM> directions = Mask::getRelativeDirections<DIM >(m_direction);
   for(uint32_t d=0; d<DIM; ++d)
   {
       if (m_directions[d] == 1)
            result[d] = this->getGridSuperCells()[d] - this->getGuardingSuperCells() - this->getBorderSuperCells();
   }
   resturn result;
}
```

**Comment by Flamefire** [comment]
You are right. Rebased and reimplemented. Please check the new code.

**Comment by psychocoderHPC** [comment]
thx for this nice mapper

**Pull request merged**
