### PR TITLE
Fix 2D implementation of incident GaussianBeam

### LINKED ISSUE #4249: Dimension dependent Gouy Phase
In GaussianBeam.hpp there seems to be a mistake with the Gouy Phase xi (line 254) - 
for a 3D simulation it is implemented correctly, but in case of a 2D simulation it has to be multiplied by 0.5,  I think.

### PR DESCRIPTION
**Pull request by steindev**
fix  #4249

Spotted and originally authored by @fabidie. 

Separating this from PR #4279.

### CODE REVIEW

**Review by PrometheusPi — DISMISSED** [review]
lgtm

**Comment by PrometheusPi** [comment]
@psychocoderHPC Is our CI still running? 
This pr is 19h old and the CI did not yet finish checking it.

**Comment by steindev** [comment]
> @psychocoderHPC Is our CI still running? This pr is 19h old and the CI did not yet finish checking it.

My fault. I assigned you to this PR which (still) makes the CI fail. I `git commit --amend; git push -f` to trigger the CI again.

**Review by PrometheusPi — APPROVED** [review]
still looks good to me

**Pull request merged**
