### PR TITLE
Use correct device number

### PR DESCRIPTION
**Pull request by Flamefire**
The wrong device ID was used in the request

### CODE REVIEW

**Comment by psychocoderHPC** [comment]
This bug affects the master. Do to the reason that it only write out wrong device properties but not influence any other points a **back port is not** needed.

**Comment by Flamefire** [comment]
@psychocoderHPC I still would recommend a backport as it is a 1-line fix which is unlikely to cause problems and the bug can lead to confusion. Consider someone publishing some results saying he used THIS accelerator but actually another one was used...

**Comment by ax3l** [comment]
that's ok, I'll cherry-pick it in the `0.1.1` release branch.

**Comment by ax3l** [comment]
causes some merge conflicts, but I'll put it in.

**Pull request merged**
