### PR TITLE
Clean Bunch example

### PR DESCRIPTION
**Pull request by steindev**
Remove `components.param` and `starter.param` since they are equal to the standard files.

### CODE REVIEW

**Comment by steindev** [comment]
By the way, there is a definition of `inCellPosition` as well as `InCellPosition` in `particle.param` of this example. I guess one of these can be removed as well?

**Comment by steindev** [comment]
@psychocoderHPC or @PrometheusPi: Are you able to restart the single CI job that failed?

Ohh wait. Actually, could you first answer the question in the previous post, please?

**Comment by PrometheusPi** [comment]
@steindev done

**Comment by PrometheusPi** [comment]
@steindev I do not find neither the string `inCellPosition` nor `InCellPosition` in the current [`particle.param`](https://github.com/ComputationalRadiationPhysics/picongpu/blob/abb173ffa2abcaee7e4a036737b7a7e241b66c8d/share/picongpu/examples/Bunch/include/picongpu/param/particle.param)

Only `inCellOffset` and its templated datatype `InCellOffset_t`.

**Comment by PrometheusPi** [comment]
The CI job failed again - this time a looked into the error message: openMP could not e found (despite being an optional dependency, this is marked as error)

**Comment by steindev** [comment]
> The CI job failed again - this time a looked into the error message: openMP could not e found (despite being an optional dependency, this is marked as error)

This is the same error as before. I wonder why it happens just for this single configuration. The other openMP job with g++ did work.

**Comment by steindev** [comment]
> @steindev I do not find neither the string `inCellPosition` nor `InCellPosition` in the current [`particle.param`](https://github.com/ComputationalRadiationPhysics/picongpu/blob/abb173ffa2abcaee7e4a036737b7a7e241b66c8d/share/picongpu/examples/Bunch/include/picongpu/param/particle.param)
> 
> Only `inCellOffset` and its templated datatype `InCellOffset_t`.

So there is a definition of a `float_X` vector with three components and name `InCellOffset` in [line 84](https://github.com/ComputationalRadiationPhysics/picongpu/blob/abb173ffa2abcaee7e4a036737b7a7e241b66c8d/share/picongpu/examples/Bunch/include/picongpu/param/particle.param#L84) which does not seem to be used anywhere.

And there is a definition of a variable `inCellOffset` of type `InCellOffset_t` in [line 97](https://github.com/ComputationalRadiationPhysics/picongpu/blob/abb173ffa2abcaee7e4a036737b7a7e241b66c8d/share/picongpu/examples/Bunch/include/picongpu/param/particle.param#L97) which does not appear to be set to a value.

This confuses me.

**Comment by PrometheusPi** [comment]
@steindev you are right. And this is wired. [`inCellOffset`](https://github.com/ComputationalRadiationPhysics/picongpu/blob/abb173ffa2abcaee7e4a036737b7a7e241b66c8d/share/picongpu/examples/Bunch/include/picongpu/param/particle.param#L97) is never defined. Since [`InCellOffset`](https://github.com/ComputationalRadiationPhysics/picongpu/blob/abb173ffa2abcaee7e4a036737b7a7e241b66c8d/share/picongpu/examples/Bunch/include/picongpu/param/particle.param#L84) is a typo (it is not camel case) and should be  `inCellOffset`. 

Why didn't the compile test catch this? 

[Case 5](https://github.com/ComputationalRadiationPhysics/picongpu/blob/abb173ffa2abcaee7e4a036737b7a7e241b66c8d/share/picongpu/examples/Bunch/cmakeFlags#L37) should fail.

**Comment by PrometheusPi** [comment]
@psychocoderHPC do you understand, why case 5 is not checked? 
(Do we check subcases at all?)

**Review by psychocoderHPC — DISMISSED** [review]

**Comment by psychocoderHPC** [comment]
```C++
// sit directly in lower corner of the cell
            CONST_VECTOR(
                float_X,
                3,
                InCellOffset,
                /* each x, y, z in-cell position component in range [0.0, 1.0) */
                0.0,
                0.0,
                0.0);
```

Is the definition and is creating a type `InCellOffset_t`. In line 97 `const InCellOffset_t inCellOffset;` the definition is used to create a member for the struct with the name `inCellOffset`.
`inCellOffset` is a required member by OnePositionImpl https://github.com/ComputationalRadiationPhysics/picongpu/blob/abb173ffa2abcaee7e4a036737b7a7e241b66c8d/include/picongpu/particles/startPosition/OnePositionImpl.hpp#L74-L84

UNfortionally even the def file for `OnePositionImpl`  is not mentioning the required name to fulfill the interface.

The position functors following the manipulator requirements and style where we typically provide an example how the param struct must look like see: https://github.com/ComputationalRadiationPhysics/picongpu/blob/abb173ffa2abcaee7e4a036737b7a7e241b66c8d/include/picongpu/particles/manipulators/unary/Drift.def#L37-L49 
Unfortionally all start position functors lacking this example struct to show the user the required interface.

**Comment by psychocoderHPC** [comment]
> @psychocoderHPC or @PrometheusPi: Are you able to restart the single CI job that failed?
> 
> Ohh wait. Actually, could you first answer the question in the previous post, please?

I restarted the failing CI job

**Comment by psychocoderHPC** [comment]
@steindev I do not know why the CI issue is now showing up but I think the issue should be fixed with #4420

**Review by PrometheusPi — APPROVED** [review]

**Pull request merged**
