### PR TITLE
fix missing namespace

### PR DESCRIPTION
**Pull request by psychocoderHPC**
add namespace splash to used `DataCollector`

### CODE REVIEW

**Comment by PrometheusPi** [comment]
How did this work previously?

**Comment by psychocoderHPC** [comment]
I don't know.

**Comment by ax3l** [comment]
ftr: probably via a weird include order, we write `using namespace splash;` too often.

**Comment by ax3l** [comment]
late update: the reason it was broken might have been the update to libSplash 1.2.4+ in #642

**Pull request merged**
