### PR TITLE
remove example: ThermalTest

### PR DESCRIPTION
**Pull request by psychocoderHPC**
The thermal test is since years not maintained or used.
Additionally, we like to reduce the CUSTL dependencies. This test is based on CUSTL.
An additional benefit of removing this test is that our CI will have to check fewer examples^^.
If such a test is required there is no problem to introduce a new tested example/test.

- [x] please do not merge until @steindev @PrometheusPi are giving green light via a review

### CODE REVIEW

**Comment by PrometheusPi** [comment]
@psychocoderHPC I agree with you that this example is outdated and currently does not serve us as test case anymore. 
On the other hand implementing a test equivalent to this example would be great. However, this requires new methods, like the ones you are currently implementing in `[topic-openPMDSlicing3](https://github.com/psychocoderHPC/picongpu/tree/topic-openPMDSlicing3)`. 

Thus: Why do you want an explicit green light from  @sbastrakov and me? (Did I miss something here?) 

What do you think of re-implementing this example as test later on (after removing this ThermalTest example)?

**Comment by PrometheusPi** [comment]
@psychocoderHPC and @steindev Is #4099 already an equivalent test?

**Comment by psychocoderHPC** [comment]
> @psychocoderHPC and @steindev Is #4099 already an equivalent test?

I do not think that this test is equivalent because what I know from the past was shown somehow which plasma frequencies can be resolved with PIC.

**Comment by psychocoderHPC** [comment]
> Thus: Why do you want an explicit green light from @sbastrakov and me? (Did I miss something here?)

I would like to have a green light from two physicists to avoid deleting something useful and required.

My point of view: I see only code an example that was not executed for 10+ years.

**Comment by PrometheusPi** [comment]
Okay - I think such a test is in general very useful - but you are right - if the test has not been executed for more than 10 years - it is better to remove it and build it from scratch as a real test. 
(Green light from my side.)

**Review by PrometheusPi — APPROVED** [review]

**Comment by steindev** [comment]
> Okay - I think such a test is in general very useful - but you are right - if the test has not been executed for more than 10 years - it is better to remove it and build it from scratch as a real test. (Green light from my side.)

I agree. There is actually an open issue I have on my plate... #3596

**Review by steindev — APPROVED** [review]

**Pull request merged**
