### PR TITLE
Field absorber test example

### PR DESCRIPTION
**Pull request by sbastrakov**
This is a new input setup, which will demonstrate use of absorbers and can be used for testing their absorption performance.

I've taken the single particle test example and add background J to simulate an antenna in the center (this is often used in the literature for absorber tests).

Currently it is a draft, needs more work.

- [x] merge after #2950

### CODE REVIEW

**Comment by PrometheusPi** [comment]
@sbastrakov great job - how much does the time required by the compile suite increase with this amount of tests?

**Comment by sbastrakov** [comment]
@PrometheusPi that's a good point that I did not think of. Each case is relatively small since it does not deal with particles, but there are so many of them. I think for testing that it compiles only one case per absorber is actually needed. Others are there for evaluating efficiency of absorption and demonstrating reasonable parameters if a user wants to have a look.

**Comment by sbastrakov** [comment]
Ready for review.
But should not be merged before #2950, some of the setups also should not compile before that.

**Comment by sbastrakov** [comment]
In the build log there is a spack-related errors, like

```
Error: the constraint '['boost', '%gcc@4.9.4']' matches multiple packages:
	tlgi5ua boost@1.62.0%gcc@4.9.4+atomic+chrono~clanglibcpp~context~coroutine cxxstd=98 ~date_time~debug+exception~fiber+filesystem~graph~icu~iostreams~locale~log+math~mpi+multithreaded~numpy patches=2ab6c72d03dec6a4ae20220a9dfd5c8c572c5294252155b85c6874d97c323199 ~pic+program_options~python~random+regex+serialization+shared+signals~singlethreaded+system~taggedlayout+test~thread~timer~versionedlayout~wave arch=linux-ubuntu14.04-x86_64
	ls2pzm3 boost@1.65.1%gcc@4.9.4+atomic+chrono~clanglibcpp~context~coroutine cxxstd=98 ~date_time~debug+exception~fiber+filesystem~graph~icu~iostreams~locale~log+math~mpi+multithreaded~numpy patches=2ab6c72d03dec6a4ae20220a9dfd5c8c572c5294252155b85c6874d97c323199 ~pic+program_options~python~random+regex+serialization+shared+signals~singlethreaded+system~taggedlayout+test~thread~timer~versionedlayout~wave arch=linux-ubuntu14.04-x86_64
```

I believe it is an issue of spack or our CI, and unrelated to the PR changes. @ax3l, could you take a look?

**Comment by psychocoderHPC** [comment]
It is a travis cache issue since we updated boost to 1.65.1. (thx @ax3l to find the issue). I triggered the CI again.

**Comment by sbastrakov** [comment]
Okay, now the checks have passed. @psychocoderHPC and/or @PrometheusPi please review when you have time (this is not that urgent).

**Comment by ax3l** [comment]
@sbastrakov it's generally good if we can combine such tests with existing examples to save CI time, but if this helps to be separate I am ok with it :)

Can you please add a `README.rst` to the new example? That way, readers will know how to use it.
Also, do not hesitate to check in little python scripts in its `bin/` directory that do the automated analysis when run.

**Comment by sbastrakov** [comment]
@ax3l good point, will look into it.

**Comment by ax3l** [comment]
Thanks!
`FoilLCT` might be an example that demonstrates that well, but feel free to check all examples.

**Pull request merged**
