### PR TITLE
Upgrade to Boost 1.66

### PR DESCRIPTION
**Pull request by bernhardmgruber**
This PR raises the minimum required Boost version to 1.66.0, which is the first release to support Boost.Mp11, which is a prerequisite vor #3834.

- [x] rebase against #3942

### CODE REVIEW

**Comment by bernhardmgruber** [comment]
One of the CI jobs fails with:
```
[ 69%] Building CUDA object CMakeFiles/picongpu.dir/main.cpp.o
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
Killed
make[2]: *** [CMakeFiles/picongpu.dir/build.make:76: CMakeFiles/picongpu.dir/main.cpp.o] Error 137
```
Any idea what is causing this?

**Comment by psychocoderHPC** [comment]
#3942 hopefully will solve the issue. You need to rebase against #3942 anyway to be able to pass HIP tests.

**Comment by bernhardmgruber** [comment]
> #3942 hopefully will solve the issue. You need to rebase against #3942 anyway to be able to pass HIP tests.

I will rebase when you have merged the PR.

**Comment by psychocoderHPC** [comment]
Please rebase against the current dev branch to pull the latest fixes to be able to pass the CI.

**Review by psychocoderHPC — APPROVED** [review]

**Pull request merged**
