### PR TITLE
Fix syntax error in SingleParticleTest configuration file.

### PR DESCRIPTION
**Pull request by mikewang2000**

### CODE REVIEW

**Review by sbastrakov — APPROVED** [review]

**Comment by sbastrakov** [comment]
Thanks for providing a fix @mikewang2000 !

**Review by PrometheusPi — APPROVED** [review]

**Comment by PrometheusPi** [comment]
@mikewang2000 Thank you for your quick pull request.

**Comment by mikewang2000** [comment]
Great, thanks for your quick response.

**Comment by psychocoderHPC** [comment]
@mikewang2000 Thanks for your first pull request to PIConGPU! :heart:

**Pull request merged**
