### PR TITLE
Fix two typos in pic-create output

### PR DESCRIPTION
**Pull request by sbastrakov**

### CODE REVIEW

**Review by steindev — APPROVED** [review]

**Review by PrometheusPi — APPROVED** [review]

**Comment by sbastrakov** [comment]
@psychocoderHPC travis unit tests fail with
`==> Error: module 'spack.hooks' has no attribute 'sbang'****`, and before that there is `Warning: detected deprecated properties in /home/travis/.cache/spack/etc/spack/packages.yaml` which may be the reason.

**Comment by psychocoderHPC** [comment]
@sbastrakov Please do **not** push branches to the mainline. Please check that this branch is removed after we merged it.

**Comment by sbastrakov** [comment]
Ah, sorry, I edited on github and didn't realize what happened.

**Comment by psychocoderHPC** [comment]
I will merge this PR, the CI issue can not be related to this PR and is maybe also triggered because the source branch is in the PIConGPU repo instead of the own fork.

**Review by psychocoderHPC — APPROVED** [review]

**Comment by psychocoderHPC** [comment]
@sbastrakov I deleted the branch already.

**Pull request merged**
