### PR TITLE
clean field solver DS float usage

### PR DESCRIPTION
**Pull request by psychocoderHPC**
- change `float` to `float_X`
- cast floating point scalars to `float_X`

### CODE REVIEW

**Comment by ax3l** [comment]
thx, I can take that pull

**Comment by PrometheusPi** [comment]
@psychocoderHPC Could you please update the license year. :blush:

**Comment by ax3l** [comment]
this file will get more updates very soon ;)

**Comment by Heikman** [comment]
I have adopted your changes to my DS branch, so you don't need to update the license year ;) and we don't have any pull requests for DS to dev anymore.

**Comment by Heikman** [comment]
we will update the license year in a follow up to avoid merge conflicts

**Pull request merged**
