### PR TITLE
Ascent (ORNL) setup

### PR DESCRIPTION
**Pull request by PrometheusPi**
This pull request adds the setup for the Ascent (test cluster) at ORNL.

### CODE REVIEW

**Comment by PrometheusPi** [comment]
Should I update the profile to point to our shared libraries? (Which would however only be readable to our project.)

**Comment by sbastrakov** [comment]
I think that would work only during the hackathon? Then probably not worth, and the installation and settings you made at the shared directory were already helpful and sufficient. Having Ascent profile in general still has value, in case some user will have access to it in the future.

**Comment by PrometheusPi** [comment]
@sbastrakov Okay, then it can be reviewed and merged as is. Changed the status from *draft* to *open*.

**Review by sbastrakov — APPROVED** [review]

**Review by sbastrakov — CHANGES_REQUESTED** [review]
Please also add it to this doc page: https://github.com/ComputationalRadiationPhysics/picongpu/blob/dev/docs/source/install/profile.rst

**Comment by PrometheusPi** [comment]
@sbastrakov I will add a documentation to the `profile.rst` file - thanks for pointing this out :+1: 
Do you know why we keep a copy (not link as far as I can tell) of the profiles in `picongpu/docs/source/install/profiles`? 
Should a add a copy/link as well?

**Review by sbastrakov — APPROVED** [review]

**Pull request merged**
