### PR TITLE
Release 0.4.1

### PR DESCRIPTION
**Pull request by ax3l**
Collection of all relevant PRs for the `release-0.4.1` branch in the next days/weeks.
Update to `0.4.1`.

Thanks to @ax3l, @psychocoderHPC, @PrometheusPi, and @berceanu for contributing to this release!

## Bug Fixes

- PIConGPU:
  - [x] avoid sliding twice in some corner-cases #2774
  - [x] EveryNthCell: broken if not used with same spacing #2768
  - [x] broken compile with particle merging #2753
- Examples:
  - [x] fix outdated derive species #2756
  - [x] remove current deposition in bunch example #2758
  - [x] fix 2D case of single electron init (via density) #2766
- Tools:
  - [x] Python Regex: r Literals #2767
  - [x] `cuda_memtest`: avoid noisy output if NVML is not found #2785

## Misc

- [x] bump version to `0.4.1-rc1`
- [x] update `CHANGELOG.md` with [rc1](https://github.com/ComputationalRadiationPhysics/picongpu/pull/2784) changes
- [x] Params: remove `boost::vector<>` usage #2769 
- Docs:
  - [x] Spack: Improve Bootstrap #2773
  - [x] Fix docs for radiation in 2D #2772
  - [x] Containers: Update 0.4.0 #2750
  - [x] Update Readme & License: People #2749
  - [x] Add `.zenodo.json` #2747

### CODE REVIEW

**Comment by berceanu** [comment]
Will https://github.com/ComputationalRadiationPhysics/picongpu/pull/2731 be included in `0.4.1`?

**Comment by ax3l** [comment]
@psychocoderHPC ping ready for merge :)

**Comment by ax3l** [comment]
I can also make this immediately `0.4.1` without `rc` if you like

**Comment by ax3l** [comment]
done, I did like it ;-)

**Comment by ax3l** [comment]
ping @psychocoderHPC

**Pull request merged**
