### PR TITLE
add namespace prefix to max function call

### PR DESCRIPTION
**Pull request by Heikman**
add namespace prefix to max function call

### CODE REVIEW

**Comment by PrometheusPi** [comment]
:+1:

**Comment by ax3l** [comment]
@PrometheusPi @Heikman pls open an other pull request to update [other calls](https://github.com/ComputationalRadiationPhysics/picongpu/tree/822fbae1de44ea208793a2e2971fc71f0a9d3c66/src/libPMacc/include/math/vector/math_functor), too!

These "half-changed" pull requests help noone. Also, the description of the issue does not tell why the change was necessary (maybe someone in the future encounters a similar problem?). Please add.

**Comment by PrometheusPi** [comment]
@ax3l I will do that. Thanks for reminding us.

**Comment by ax3l** [comment]
@Heikman pls add a description why the refactoring was necessary: compile problems (where? with what compiler?), naming collisions, ... :)

**Pull request merged**
