### PR TITLE
Add pragma once where it was missing and change ifdef guards

### PR DESCRIPTION
**Pull request by Flamefire**
I used the commands

    find . -name "*.hpp" -print | xargs grep -iL "pragma once"
    find . -name "*.tpp" -print | xargs grep -iL "pragma once"
    find . -name "*.def" -print | xargs grep -iL "pragma once"

to find files where pragma once was missing. In some cases (e.g. ~21 tpp files) no header guard was present at all which can cause problems when including them multiple times. As pragma once is the new standard I also removed the old header guards and replaced them by pragma once so the above commands don't list relevant files

### CODE REVIEW

**Comment by psychocoderHPC** [comment]
Did you checked the folder `examples`?

**Comment by ax3l** [comment]
thanks! :)

(but the change is *very* close to an automated/trivial change that we usually commit under a [generic user](https://github.com/ComputationalRadiationPhysics/picongpu/issues/755) without updating the license header...)

**Comment by Flamefire** [comment]
@psychocoderHPC Yes (see changed files)
What I did not change were headers that only include other headers (e.g. CurrentInterpolation.def,  Solver.def)

@ax3l I was wondering if this counts as a big enough change to change the header. However although trivial this could not be done automatically without special tools. I hope it is ok this time, as reverting the header of >100 files would still be quite some work or is there a tool for that?

**Comment by psychocoderHPC** [comment]
big thanks!

**Pull request merged**
