### PR TITLE
Third Party: cuda_memtest update

### PR DESCRIPTION
**Pull request by ax3l**
This PR updates `cuda_memtest` with the latest updates from our [upstream repository](https://github.com/ComputationalRadiationPhysics/cuda_memtest):
  https://github.com/ComputationalRadiationPhysics/cuda_memtest/pull/2
  https://github.com/ComputationalRadiationPhysics/cuda_memtest/pull/3
  https://github.com/ComputationalRadiationPhysics/cuda_memtest/pull/4
  https://github.com/ComputationalRadiationPhysics/cuda_memtest/pull/6 (follow up of #1156)

Updated via:
```bash
GIT_AUTHOR_NAME="Third Party" GIT_AUTHOR_EMAIL="picongpu@hzdr.de" \
  git subtree pull --prefix thirdParty/cuda_memtest/ \
  git@github.com:ComputationalRadiationPhysics/cuda_memtest.git dev --squash
```

### CODE REVIEW

**Comment by PrometheusPi** [comment]
I will trust the maintainers of cuda_memtest :smile:

**Comment by ax3l** [comment]
(which are currently identical to PIConGPU maintainers ;) )

**Comment by bussmann** [comment]
now I'm worried.

**Comment by ax3l** [comment]
in commits we trust.

**Pull request merged**
