### PR TITLE
Version bump: openPMD-api from 0.12.0 to 0.14.3

### PR DESCRIPTION
**Pull request by franzpoeschel**
openPMD-api version 0.14.3 has recently been [released](https://github.com/openPMD/openPMD-api/commit/00532a7873f1ec3eff9aa4238f303597bd039b6b) and includes fixes that are necessary for usage with C++17. With older versions, there are ABI incompatibilities if building openPMD-api with C++14, but including it into a C++17 project.

Since PIConGPU is currently being released (still on C++14), this marks a good time for bumping the minimum required version once the release is out. This also removes a number of workarounds for newer features (namely: the streaming API, the span-based storeChunk() API, dataset-specific backend configuration) that were not available in openPMD-api 0.12.0.

TODO:
- [x] Maybe wait for PIConGPU release before merging this into dev
- [x] Update CI containers ([see also](https://gitlab.com/hzdr/crp/alpaka-group-container/-/merge_requests/30))
- [x] Check HDF5 still working in parallel
    Update: There seem to be issues with chunking. This can be deactivated, but should be clarified before merging this one.

### CODE REVIEW

**Comment by psychocoderHPC** [comment]
@franzpoeschel The PIConGPU release branch is already open, so we can update the requirements of the dev branch at any time.

**Comment by psychocoderHPC** [comment]
I opened the PR to update the CI container #3934. 
@franzpoeschel I will notify you as soon as the PR is merged.

**Comment by psychocoderHPC** [comment]
Please rebase against the current dev branch to pull the latest fixes to be able to pass the CI.

**Comment by psychocoderHPC** [comment]
The CI found some issues

**Comment by franzpoeschel** [comment]
Ah, I accidentally committed something which I hadn't wanted to commit. I'll fix it

**Review by psychocoderHPC — APPROVED** [review]

**Comment by psychocoderHPC** [comment]
Mhh, I merged it and realized that it would be a good idea to check if we have the required modules on hemera. We do not have it :-(

**Pull request merged**
