### PR TITLE
Fix radiation plugin misleading filename

### PR DESCRIPTION
**Pull request by PrometheusPi**
This pul request renames a misleading file name `parameters.hpp` used in the radiation plugin that actually just defined various vector types.

### CODE REVIEW

**Comment by PrometheusPi** [comment]
@sbastrakov I will do that

**Comment by sbastrakov** [comment]
@PrometheusPi as an afterthought: all files for this plugin are named starting with a lowercase letter, maybe more reasonable to change all at once in a new PR (not necessarily soon, as this is just a style thing).

**Comment by PrometheusPi** [comment]
@sbastrakov but still a god idea. I will apply those changes (for the other files) in a follow-up pull request.

**Comment by PrometheusPi** [comment]
Yes, I did s regex scan for anything containing `*Config.param` on the entire repo.

**Pull request merged**
