### PR TITLE
Close #707 Document Unit Trait for Plain Numbers

### LINKED ISSUE #707: flag unit - radiation without meaning/definition
What happens [here](https://github.com/ComputationalRadiationPhysics/picongpu/blob/a5c2e9e86ce7724f0f91b4b75df8fca2e5786415/src/picongpu/include/simulation_defines/unitless/speciesAttributes.unitless#L49-L57)?

Why does the radiation flag has a undefinded unit?

### PR DESCRIPTION
**Pull request by n01r**
Is this small change how the comments on the unitless flags should look like and should the other ones also get more comments? 

I also changed the indents from 2 spaces to our 4 space standard. Was that correct?

### CODE REVIEW

**Comment by ax3l** [comment]
pls put the docs before the `get` definition as  a documentation what it implements

pls avoid unnecessary white space changes

pls add the documentation that "zero size is valid for no unit" also to [include/traits/Unit.hpp](https://github.com/ComputationalRadiationPhysics/picongpu/blob/2994c9d31d01d714124e1e6dea7b64432a736505/src/picongpu/include/traits/Unit.hpp)

**Comment by n01r** [comment]
Why should we not enforce consistency ... even in white spaces, if we have small pull requests such as this one.

**Comment by ax3l** [comment]
The first rule of a good patch: if you check the style of the file before and after you applied the patch, the patch should not be optically visible.

since you changed it consistently according to the style guide for the whole file and all you add is documentation it is fine (if you would have added functionality it would not be :) ).

**Comment by n01r** [comment]
I understand your point - I just thought it was okay because it is consistent and there are no other changes.

**Comment by ax3l** [comment]
yep that's right. just a reflex.

pls add the two other points.

**Comment by n01r** [comment]
already done ... just squashing now

**Comment by ax3l** [comment]
top! :rocket:

**Pull request merged**
