### PR TITLE
Fix gcc 9 unused parameter error

### PR DESCRIPTION
**Pull request by ikbuibui**
Fix for the failing full CI run

### CODE REVIEW

**Review by chillenzer — APPROVED** [review]

**Review by PrometheusPi — COMMENTED** [review]
looks okay
but do we need to add `[[maybe_unused]]` to line 62 too?

**Comment by ikbuibui** [comment]
`[[maybe_unused]]` suppresses warnings about variables that might not be used in the current scope. This old compiler sees that the `superCellIndex` and `eFieldBox` are not used in the `else` branch of the `if constexpr`, so it throws a warning/error, even though they are conditionally used in the `if` branch on line 62.
`[[maybe_unused]]` isnt required on line 62 because it isnt defining any parameters which are later not used. It is only returning the cache. It is the responsibility of the caller of this function to store this cache and then use it. If the caller assigns the returned cache to a variable and then doesn't use it this warning/error will be thrown at the caller side.
Just for information, kind of similarly if you want to make sure that the return value of a function is stored (and not ignored/discarded) by the caller, you can declare the function ` [[nodiscard]]`.

**Comment by PrometheusPi** [comment]
@ikbuibui Thanks for the clarification. Thant makes sense, I was following the documentation example [here](https://en.cppreference.com/w/cpp/language/attributes/maybe_unused) and was a bit confused.

**Review by PrometheusPi — APPROVED** [review]

**Review by psychocoderHPC — APPROVED** [review]

**Comment by psychocoderHPC** [comment]
Thanks @ikbuibui I planed to fix it too, good that I checked the PRs first

**Pull request merged**
