### PR TITLE
[WIP] Add unit tests for PMaccLib Bessel functions

### PR DESCRIPTION
**Pull request by BeyondEspresso**
Here we add a few unit tests for testing the real and complex Bessel functions of PMaccLib. Emphasis is on the complex BesselJ0 and BesselJ1 implementation. The goal was to test every important value range in the complex plane that is associated with an own decision branch in the implementation. Note that currently, everything is still calculated on the CPU and not on the device.

This pull request is in no hurry! Feedback and suggestions for improvement are welcome.

- [x] rebase after #2161 is merged
- [ ] RT test

### CODE REVIEW

**Comment by BeyondEspresso** [comment]
This is an in between status: I now added a complex bessel test on the device. Compiles, but is not tested yet.

**Comment by PrometheusPi** [comment]
@BeyondEspresso What is the status of this pull request?

**Comment by psychocoderHPC** [comment]
I set this PR to `draft` because there is no progress.

**Comment by psychocoderHPC** [comment]
I will close this PR no update for 5 years and we switched the testing framework in the mean time.

**Pull request closed without merging**
