### PR TITLE
Doc: C++14

### PR DESCRIPTION
**Pull request by ax3l**
PIConGPU is now a C++14 code. Updates CMake files and README badge.

Follow-up to #3242

### CODE REVIEW

**Comment by ax3l** [comment]
Is our compile node down? Maybe @PrometheusPi can you reach out to Cluster IT and CC my LBL mail? This is what I see:
```
huebl@hemera5:~$ ssh icn019a
ssh: connect to host icn019a port 22: No route to host
```

**Comment by PrometheusPi** [comment]
@ax3l I will do that.

**Comment by PrometheusPi** [comment]
@ax3l The server is now up and running again.

**Comment by ax3l** [comment]
@PrometheusPi ready for merge :)

**Comment by PrometheusPi** [comment]
@ax3l Thanks for the reminder/ping.

**Pull request merged**
