### PR TITLE
LiveVis: Add Client

### PR DESCRIPTION
**Pull request by ax3l**
This is the Qt `client` follow up #641.
It can be compiled with the recent release of [rivlib](https://github.com/ComputationalRadiationPhysics/rivlib).

# State of this tool

@psychocoderHPC and me cleaned, fixed and upgraded this tool.
A `README.md` was added and some useful scripts for tunneling.

**Note:** Feel free to provide pull requests to improve the quality of the tool.

# Acknowledgments

A big thank you to @Ben-Schneider as the author of the tool!
Kudos also to @SGrottel-TUD and  as the author of [rivlib](https://github.com/ComputationalRadiationPhysics/rivlib) and to @tud-mkalms for the support and new image stream implementations last year.

# To Do

#754: If one can not reach the cluster's head node directly, the `./tunnel2cluster.sh` script helps a lot.
In that case, the ip in [DEFAULT_SERVER_IP](https://github.com/ax3l/picongpu/blob/ee6dcb767ee67756ed46d9263cf798935973122a/src/tools/livevis/client/main.cpp#L4) must be set to "127.0.0.1" and the actual *hostname*, e.g. `hypnos5` must be listed in `/etc/hosts` as `127.0.0.1 hosts` (because rivlib announces it in the uri by *name*).

- [x] add license headers (GPL for now, AGPL later?)

### CODE REVIEW

**Comment by ax3l** [comment]
I think we should merge this, add an issue for the `/etc/hosts` problem and add a documentation page consisting of the description of this pull request to the wiki.

**Comment by psychocoderHPC** [comment]
We need to add a licence.

**Comment by ax3l** [comment]
@psychocoderHPC added and rebased to current `dev` - ready for merge

**Comment by ax3l** [comment]
- [ ] waiting for command-line option bug fix from https://github.com/ax3l/picongpu/pull/4

**Comment by ax3l** [comment]
@psychocoderHPC pls merge

**Pull request merged**
