### PR TITLE
Fix #2029 MPL Embedded Plots Sphinx

### LINKED ISSUE #2029: Docs SVG: Ionization
As with the PIConGPU logo, we need to create `.pdf` alternatives of the `.svg` images for `.. only:: latex` for `make latexpdf`

also, html build on RTD seems to forget copying the live created new images (`make html`)

fixing via http://matplotlib.org/sampledoc/extensions.html

### PR DESCRIPTION
**Pull request by ax3l**
Fix #2029 by using the official matplotlib (MPL) sphinx extension to embed plots on-the-fly.

Also fixed broken `make latexpdf` compile in usage of own align (use [nowrap](http://stackoverflow.com/questions/24867685/aligned-equations-with-mathjax-and-with-equation-numbers)).

Note:
- this might need regressions after merge, e.g. to set `agg` as backend by hand

### CODE REVIEW

**Comment by ax3l** [comment]
@PrometheusPi wuhu, tests are done :)

**Comment by n01r** [comment]
I tried adding a caption to the `.. plot::` directive but somehow that didn't work. Even though I looked it up and it seemed possible. ^^;

**Comment by ax3l** [comment]
@n01r nah it's not. maybe a hidden option but I did not find it in the docs. did you find a list of available options?

**Comment by n01r** [comment]
Nope - had a look before leaving today and just found an issue.
https://github.com/matplotlib/matplotlib/issues/2850

**Comment by PrometheusPi** [comment]
@ax3l Do we want to add the fix suggested by @aa956 or do we just live without caption?
Why is the test suite pending while the pull request is already merged and you already deleted the branch?

**Comment by ax3l** [comment]
@PrometheusPi there seems to be no caption with this plugin, so we moved the caption back to the title for now

**Pull request merged**
