### PR TITLE
CUDA 9.2 & Alpaka 0.3.2

### PR DESCRIPTION
**Pull request by ax3l**
Update documentation and CMake scripts for CUDA 9.2 support.

- [x] update alpaka to 0.3.2

Update alpaka from 
 - release  alpaka@0.3.1 (ComputationalRadiationPhysics/alpaka@7d3e6ddfb9f8fb834d8895e11aa0d767e39e7b58 == [`0.3.1`](https://github.com/ComputationalRadiationPhysics/alpaka/tree/0.3.1) )
to
 - release  alpaka@0.3.2 (ComputationalRadiationPhysics/alpaka@847aed6 == [`0.3.2`](https://github.com/ComputationalRadiationPhysics/alpaka/tree/0.3.2) )

# Changes to Last Stable

Bugs Fixed:

- fixed missing error in case of wrong OpenMP thread count being used by the runtime that was not triggered when not in debug mode
- fixed CUDA driver API error handling
- fixed CUDA memcpy and memset for zero sized buffers (division by zero)
- fixed OpenMP 4 execution
- fixed the VS2017 CUDA build (not officially supported)
- fixed CUDA callback execution not waiting for the task to finish executing
- fixed cudaOnly test being part of make test when cuda only mode is not enabled

Compatibility Changes:

- added support for CUDA 9.2

# Used Update Command
```
GIT_AUTHOR_NAME="Third Party" GIT_AUTHOR_EMAIL="picongpu@hzdr.de" \
  git subtree pull --prefix thirdParty/alpaka \
  git@github.com:ComputationalRadiationPhysics/alpaka.git 0.3.2 --squash
```

### CODE REVIEW

**Comment by psychocoderHPC** [comment]
maybe alpaka will be released in today, if so than we will update directly to the release.

**Comment by BenjaminW3** [comment]
The alpaka release is out! 🎉

**Comment by psychocoderHPC** [comment]
I updated this PR with the latest alpaka bugfix release

**Comment by ax3l** [comment]
@psychocoderHPC look alright, can you merge it? :)

**Pull request merged**
