### PR TITLE
remove PIConGPU install description using spack

### PR DESCRIPTION
**Pull request by psychocoderHPC**
Our spack recipe is not maintained and no PIConGPU developer/maintainer is using spack to use PIConGPU. To avoid users getting frustrated by the broken spack recipe the documentation is currently removed until we support and test the spack workflow.
The documentation of how the dependencies of PIConGPU can be installed with spack is still available.

Latest PIConGPU version with documentation referencing the spack
workflow: https://github.com/ComputationalRadiationPhysics/picongpu/commit/5d241da2ab80a53d3c6e91206e022a22a0e1b54d

**note** Before we reintroduce a spack recipe we should modernize our CMake script and add an install action. This was something we emulated in the spack recipe and is hard to maintain.

### CODE REVIEW

**Review by PrometheusPi — DISMISSED** [review]
removing looks good to me 
Since @BrianMarre uses spack, he should comment wether his workflow relies on this.

**Comment by BrianMarre** [comment]
It does not, I have recreated our module system profiles for spack, so different workflow to what Rene is referencing

**Review by PrometheusPi — APPROVED** [review]

**Comment by cbontoiu** [comment]
As one of the few users of PIConGPU on Spack I must say thanks for all your support, sometimes related to Spack!

**Comment by psychocoderHPC** [comment]
@cbontoiu You can still manage all your required dependencies with spack. We only removed the suggestion to use the broken picongpu spack recipe until we cleaned up PIConGPU to write a clean recipe and test this in the CI.

**Pull request merged**
