### PR TITLE
Further refactor libPMacc

### PR DESCRIPTION
**Pull request by BenjaminW3**
Another round of refatoring libPMacc includes:
* reorder includes
* correct spelling errors
* pragma once instead of header guard for affected files

### CODE REVIEW

**Comment by ax3l** [comment]
@BenjaminW3 thank you for the updates.

to be honest, most of the points you put we submit under a anonymous/bot/script username and don't add us as an author: #755 

example in your case:
```
GIT_AUTHOR_NAME="Tools" GIT_AUTHOR_EMAIL="picongpu@hzdr.de" \
  git commit --amend
  git push -f [...]
```

that's just to keep the statistics fair, I hope you don't mind ;)

**Comment by ax3l** [comment]
and other small wish: when you update the end-of-line white spaces, can you pls run over the `examples/` directory, too? we forgot this last time in [520](https://github.com/ComputationalRadiationPhysics/picongpu/pull/520/commits)

**Comment by BenjaminW3** [comment]
Thanks for the description. I did not know where to find this information.
For white-space-only changes I already had not edited the authors.
See for example `src/libPMacc/include/traits/Limits.tpp`, `src/libPMacc/include/traits/GetValueType.hpp`, ...
I will attribute those things to the user 'Tools'!

**Comment by ax3l** [comment]
thanks that is fantastic!
(I did not check all year/author lines - that is correct, too :) )

**Comment by BenjaminW3** [comment]
I moved the whitespace changes into #887.

**Comment by ax3l** [comment]
thx!

**Comment by psychocoderHPC** [comment]
big thx

**Pull request merged**
