### PR TITLE
Async template for Juwels Booster, Crusher and Summit

### PR DESCRIPTION
**Pull request by franzpoeschel**
TODO

- [x] Cleanup
- [x] Move system specific stuff from the .cfg files to .tpl, currently the 6.cfg is for Summit, the 8.cfg for Crusher and the 4.cfg for Juwels

### CODE REVIEW

**Comment by PrometheusPi** [comment]
@franzpoeschel If I understood you correctly, this is now working on juwels. Could this me merged then?

**Comment by franzpoeschel** [comment]
I have currently based this branch on #4456 since I needed both their functionalities.
So, either we merge that first, or I have to separate them again.

**Comment by PrometheusPi** [comment]
I would go which whatever workflow is best for you. I just wanted to know the status of this PR.

**Comment by franzpoeschel** [comment]
> I would go which whatever workflow is best for you. I just wanted to know the status of this PR.

I've separated both PRs, you can review them in any order

**Review by psychocoderHPC — APPROVED** [review]

**Pull request merged**
