### PR TITLE
Ionization: update barrier suppression and energies

### PR DESCRIPTION
**Pull request by n01r**
In preparation for the upcoming ADK model, some of the non-model related changes have been removed from #922 to be implemented before. 

This pull request features:   
- some renaming of the ionization framework and relocation of includes
- ionization energies that are pinned to the particle species itself
- the atomic unit system for ionization energy input

Should be merged **before** #922!

- [x] wait till ~~#1021~~ is merged and rebase

### CODE REVIEW

**Comment by n01r** [comment]
Please merge #1021 before this pull request!

**Comment by n01r** [comment]
@ax3l @psychocoderHPC 
pls have a look

**Comment by ax3l** [comment]
Pls help us by commiting the `.param`/`.unitless` changes in a separate commit. I write the documentation for you as an example:

- `speciesDefinition.param`: only updated in the LWFA example to use the new ionization energy table
- `physicalConstants.param`: atomic unit constants for energy, e-field and time added (default used in examples)
- `physicalConstants.unitless`: `ATOMIC_UNIT_EFIELD` and `ATOMIC_UNIT_TIME` -> conversion from PIConGPU units to AU; examples and reference file updated
- `speciesAttributes.param`: new alias for `ionizationEnergies` table added (default used in examples)
- `ionizationEnergies.param`, `ionizerConfig.param`, `ionizerConfig.unitless`: reference files update (default used in examples)

-> all files (reference file and examples) catched :+1:

**Comment by ax3l** [comment]
@n01r pls rebase

**Comment by n01r** [comment]
@ax3l Here you go!

**Comment by ax3l** [comment]
very well done, thx! :sparkles:

**Pull request merged**
