### PR TITLE
License Header: Update to 2016

### PR DESCRIPTION
**Pull request by ax3l**
Updating years in header files is cumbersome, so we update all files to include 2016 at once.

Updated via
```bash
grep -iR "Copyright 20" . | awk -F: '{print $1}' | \
  xargs -n1 -P1 -I{} sed -i 's/\(Copyright 20..\) /\1-2016 /g' {}
grep -iR "Copyright 20" . | awk -F: '{print $1}' | \
  xargs -n1 -P1 -I{} sed -i 's/\(Copyright 20..-201\). /\16 /g' {}
```

and commited via
```bash
GIT_AUTHOR_NAME="Tools" GIT_AUTHOR_EMAIL="picongpu@hzdr.de" \
  git [...]
```
. Happy new year! :) :star2:

### CODE REVIEW

**Comment by ax3l** [comment]
@PrometheusPi will like that, I guess.

**Comment by PrometheusPi** [comment]
@ax3l great job - I love this :smile: 
The files that I could see look great.

Some questions remain:
 - If I grep all files as you did on the current `dev`, I end up with 1070 files matching the regex `""Copyright 20"` (no `.git` files involved). 
 - There are several files with license header that do not match the above regex:
```
COPYING.LESSER
COPYING
thirdParty/mallocMC/LICENSE
thirdParty/mallocMC/src/include/mallocMC/mallocMC.hpp
thirdParty/mallocMC/src/include/mallocMC/mallocMC_prefixes.hpp
thirdParty/mallocMC/src/include/mallocMC/version.hpp
thirdParty/mallocMC/src/include/mallocMC/distributionPolicies/XMallocSIMD.hpp
thirdParty/mallocMC/src/include/mallocMC/distributionPolicies/XMallocSIMD_impl.hpp
thirdParty/mallocMC/src/include/mallocMC/alignmentPolicies/Shrink_impl.hpp
thirdParty/mallocMC/src/include/mallocMC/alignmentPolicies/Shrink.hpp
thirdParty/mallocMC/src/include/mallocMC/creationPolicies/Scatter_impl.hpp
thirdParty/mallocMC/src/include/mallocMC/creationPolicies/Scatter.hpp
thirdParty/mallocMC/src/include/mallocMC/mallocMC_overwrites.hpp
thirdParty/mallocMC/src/include/mallocMC/mallocMC_utils.hpp
thirdParty/cuda_memtest/README
thirdParty/cuda_memtest/Makefile
thirdParty/cuda_memtest/cuda_memtest.cu
thirdParty/cuda_memtest/cmake/FindNVML.cmake
thirdParty/cuda_memtest/tests.cu
thirdParty/cuda_memtest/cuda_memtest.h
thirdParty/cmake-modules/LICENSE:Copyright
src/tools/livevis/client/pictureflow.h
src/tools/livevis/client/pictureflow.cpp
```

**Comment by PrometheusPi** [comment]
Merging this pull request will probably lead to  several merge conflicts in still open pull requests.

**Comment by ax3l** [comment]
two files seem to be missing, the GPL/LGPL and thirdParty are intentionally not updated.

> Merging this pull request will probably lead to several merge conflicts in still open pull requests. 

The idea is to reduce merge conflicts in the rest of the year.

**Comment by PrometheusPi** [comment]
@ax3l 
>The idea is to reduce merge conflicts in the rest of the year.

I agree

**Comment by ax3l** [comment]
Found two files that were actually missing, one with a malformed header:
- `LICENSE.md`
- `src/libPMacc/include/math/complex/Complex.hpp`

**Comment by PrometheusPi** [comment]
offline work with @axel:

two more missing files and the rest is just third party files

**Pull request merged**
