### PR TITLE
Release 0.6.0

### PR DESCRIPTION
**Pull request by psychocoderHPC**
Merge release branch into master.
Github has changed there interface. It is no longer possible to create a tag in the Web-Interface. 
Therefore we will merge the release branch first into `master` create a local tag and push this tag to github. 
I will create a release out of the tag.
With the next release 0.7.0 we will most likely remove the master.

### CODE REVIEW

**Comment by PrometheusPi** [comment]
@psychocoderHPC should this be merges as soon as the CI passes or do you need some more time to setup a publication via zenodo/rodare?

**Comment by psychocoderHPC** [comment]
> @psychocoderHPC should this be merges as soon as the CI passes or do you need some more time to setup a publication via zenodo/rodare?

Can be merged as soon as CI passed.

**Review by PrometheusPi — APPROVED** [review]
Discussed with @psychocoderHPC - will be merged without CI passed to finish release within this year

**Comment by PrometheusPi** [comment]
@psychocoderHPC You can merge now.

**Pull request merged**
