### PR TITLE
Fix grammar error in INSTALL.md

### PR DESCRIPTION
**Pull request by steindev**
Not necessary this time, isn't it?

### CODE REVIEW

**Comment by PrometheusPi** [comment]
@ax3l please add @steindev to the developer team

**Comment by PrometheusPi** [comment]
@steindev You are now a member of the picongpu developer team (thanks @ax3l) - please just recommit your pull request, then the compile suite will check your changes.

**Comment by steindev** [comment]
Resubmit = Close this one + Open a new one?

**Comment by PrometheusPi** [comment]
@steindev No, just do:
```
git log -2
# take the last commit hash
git rebase -i #input the hash here
#change the wording of the commit message by replacing pick by r
get push -uf origin dev
```

**Comment by PrometheusPi** [comment]
@steindev Thank you for resubmitting.

**Pull request merged**
