### PR TITLE
Output Radiation detector's directions & frequencies

### PR DESCRIPTION
**Pull request by PrometheusPi**
This pull request follows the idea behind openPMD and adds information on frequencies and propagation directions computed with the radiation plugin to the hdf5 output.

This pull request adjusts also some examples since the `radiationObserver.param` needed some updates.

@RemiLehe and @ax3l Is this in agreement with todays offline discussion?

**needs:**
 - [x] #1323 to be merged

### CODE REVIEW

**Comment by ax3l** [comment]
great, what this does now is using the `openPMD` particle description (base standard) to describe the directions.

can you please already add the required `globalAttributes` to the file? When using `libSplash 1.3.0` (or it's current `dev`) the output should directly be compatible with the openPMD checker file.

**Comment by PrometheusPi** [comment]
@ax3l I will do that.

Can I write `globalAttributes` with `libSplash 1.2.4`(latest release)?

**Comment by ax3l** [comment]
yes you can write global attributes, they are just not at the position
you would expect them ;)

**Comment by PrometheusPi** [comment]
@ax3l Is the new version of libSplash now  part of the compile suite?

**Comment by ax3l** [comment]
not yet.

the PIConGPU requirements will be increased to libSplash 1.3.0+ with the update to openPMD format in the next weeks.

**Comment by ax3l** [comment]
since you are not writing `bool`s in this PR, you should be fine to go with `1.2.4` for now.

**Comment by PrometheusPi** [comment]
@ax3l and @psychocoderHPC 

The current hdf5 structure of the radiation output looks as follows:
```
/                        Group
/custom                  Group
/data                    Group
/data/10                 Group
/data/10/Amplitude       Group
/data/10/Amplitude/x     Group
/data/10/Amplitude/x/Im  Dataset {256, 2048, 1}
/data/10/Amplitude/x/Re  Dataset {256, 2048, 1}
/data/10/Amplitude/y     Group
/data/10/Amplitude/y/Im  Dataset {256, 2048, 1}
/data/10/Amplitude/y/Re  Dataset {256, 2048, 1}
/data/10/Amplitude/z     Group
/data/10/Amplitude/z/Im  Dataset {256, 2048, 1}
/data/10/Amplitude/z/Re  Dataset {256, 2048, 1}
/data/10/Detector        Group
/data/10/Detector/omega  Dataset {1, 2048, 1}
/data/10/Detector/x      Dataset {256, 1, 1}
/data/10/Detector/y      Dataset {256, 1, 1}
/data/10/Detector/z      Dataset {256, 1, 1}
/header                  Group
```

The `Amplitude` is definitely a 6D (3D complex numbers) mesh/field. Thus `Amplitude` could be the `meshesPath` from the openPMD standard.

The `Detector`'s are the axis to the `Amplitude`. As discussed *offline* in august with @ax3l, they could be interpreted as either particles or fields. Here there are more field like.

Thus my question: put all in the `meshesPath` or treat the `Detector` differntly, e.g. a separate `Axis` path?

**Comment by ax3l** [comment]
`Detector` looks all right if interpreted as a `mesh`.

Since you use a sub-group in `Amplitude`, you currently have to interpret it as `particles` if you want to keep the current structure. Otherwise, if interpreted as mesh, you would need to write it as:
```
/data/10/Amplitude       Group
/data/10/Amplitude/xIm  Dataset {256, 2048, 1}
/data/10/Amplitude/xRe  Dataset {256, 2048, 1}
/data/10/Amplitude/yIm  Dataset {256, 2048, 1}
/data/10/Amplitude/yRe  Dataset {256, 2048, 1}
/data/10/Amplitude/zIm  Dataset {256, 2048, 1}
/data/10/Amplitude/zRe  Dataset {256, 2048, 1}
```

**Comment by PrometheusPi** [comment]
@ax3l thx. I will add a new `meshesPath` and put both `Detector` and `Amplitudes` in there.

**Comment by PrometheusPi** [comment]
@ax3l Should the optional openPMD attribute `software` be set to `PIConGPU` or would you prefer `PIConGPU - Radiation Plugin`?

**Comment by ax3l** [comment]
good question, I think `PIConGPU` is fine, we are not writing `PIConGPU - libSplash Plugin` either.

**Comment by PrometheusPi** [comment]
The pull request will only work with **libSplash 1.3.0**. Currently the compile suite uses **1.2.4**. Thus the check fails.

**Comment by PrometheusPi** [comment]
Since the amplitude vector is a 3D complex vector, I structured the data and records as following:
```
/data/10/DetectorMesh/Amplitude Group
/data/10/DetectorMesh/Amplitude/x Group
/data/10/DetectorMesh/Amplitude/x/Im Dataset {256, 2048, 1}
/data/10/DetectorMesh/Amplitude/x/Re Dataset {256, 2048, 1}
/data/10/DetectorMesh/Amplitude/y Group
/data/10/DetectorMesh/Amplitude/y/Im Dataset {256, 2048, 1}
/data/10/DetectorMesh/Amplitude/y/Re Dataset {256, 2048, 1}
/data/10/DetectorMesh/Amplitude/z Group
/data/10/DetectorMesh/Amplitude/z/Im Dataset {256, 2048, 1}
/data/10/DetectorMesh/Amplitude/z/Re Dataset {256, 2048, 1}
```

Thus the [openPMD validator](https://github.com/openPMD/openPMD-validator/blob/a2c5c1770352291eacadb37e1eee5a804e71c350/checkOpenPMD_h5.py#L318-L322) interprets `.../x`, `.../y` and `.../z` as [constant records](https://github.com/openPMD/openPMD-standard/blob/latest/STANDARD.md#constant-record-components). 

However, they are only a substructure.
Should I restructure to:
```
/data/10/DetectorMesh/Amplitude Group
/data/10/DetectorMesh/Amplitude/x_Im Dataset {256, 2048, 1}
/data/10/DetectorMesh/Amplitude/x_Re Dataset {256, 2048, 1}
/data/10/DetectorMesh/Amplitude/y_Im Dataset {256, 2048, 1}
/data/10/DetectorMesh/Amplitude/y_Re Dataset {256, 2048, 1}
/data/10/DetectorMesh/Amplitude/z_Im Dataset {256, 2048, 1}
/data/10/DetectorMesh/Amplitude/z_Re Dataset {256, 2048, 1}
```
or is there a way to introduce sub-"directories" in openPMD?

**Comment by PrometheusPi** [comment]
The question was already answered yesterday - sorry I missed it. I will adjust the naming.

**Comment by PrometheusPi** [comment]
Renaming did not break the restart capability. (Run time test performed.)

**Comment by PrometheusPi** [comment]
@ax3l I is now compatable with openPMD 
as long es one moves the global attributes from `/custom` to  `/`

```python
#!/bin/bin/env python

import numpy as np
import h5py

import argparse

parser = argparse.ArgumentParser(description='Process a PIConGPU hdf5 file to work with openPMD standard.')
parser.add_argument("filename", help="filename of hdf5 file to convert")

a = parser.parse_args()


f = h5py.File(a.filename, "r+")

attributes = f["/custom/"].attrs.items()
b = f["/"]


for i in attributes:
    b.attrs.create(i[0], i[1])

f.close()
```

**Comment by ax3l** [comment]
awesome :sparkles: :+1:

**Comment by bussmann** [comment]
Fantastic work!

**Comment by PrometheusPi** [comment]
@ax3l I squashed the commits to meaningful commits.

**Comment by PrometheusPi** [comment]
@ax3l please tell me when you update the compile suite. (I have to push the pr again to trigger the check again.)

**Comment by ax3l** [comment]
will do!

**Comment by PrometheusPi** [comment]
@ax3l any changes on the compile suite so far?

**Comment by PrometheusPi** [comment]
@ax3l same question as a month ago

**Comment by ax3l** [comment]
I am with you, PR's will come.

You will need libSplash `1.4.0` (will do a PR asap).

**Comment by psychocoderHPC** [comment]
Please rebase your branch because #1427 changed the `libSplash` version to `1.4.0` and start a runtime test to verify your results.

**Comment by PrometheusPi** [comment]
@psychocoderHPC I rebased against the current `dev`. Now I just have to check the output.

**Comment by PrometheusPi** [comment]
Output passes the **openPMD-validator**
```
 python checkOpenPMD_h5.py -i .../040_libsplash_1.4.0/simOutput/radiationHDF5/radAmplitudes_2800_0_0_0.h5 
Found 1 iteration(s)
Iteration 2800 : found 3 meshes
Iteration 2800 : found 0 particle species
Result: 0 Errors and 0 Warnings.

```

**Comment by PrometheusPi** [comment]
@ax3l can be merged

**Comment by ax3l** [comment]
wonderful! :sparkles:

**Pull request merged**
