### PR TITLE
plugin sum current refactoring

### PR DESCRIPTION
**Pull request by psychocoderHPC**
Use lockstep programming to add support for any supported PIConGPU backend.

- [x] rebase against #4496

### CODE REVIEW

**Comment by PrometheusPi** [comment]
@psychocoderHPC please run `clang-format` - the CI is not happy with the code (style)

**Comment by PrometheusPi** [comment]
@psychocoderHPC there are still some compile time errors in: `SumCurrents.hpp`

**Review by PrometheusPi — APPROVED** [review]

**Comment by PrometheusPi** [comment]
@psychocoderHPC have you run any test?

**Comment by psychocoderHPC** [comment]
No, I trust my coding skills^^
But since you mentioned it I did the test now. All works as expected. I tested LWFA on CUDA GPUs.

**Comment by psychocoderHPC** [comment]
@PrometheusPi ping

**Pull request merged**
