### PR TITLE
fix warnings and check for warnings in CI

### PR DESCRIPTION
**Pull request by psychocoderHPC**
- Add CMake option `PIC_CI_COMPILE` to enable more strict compile errors.
- CI: enable strict warning/error checks
- fix compile error when using `-Wall`

We always enabled strict warnings together with GCC but never enabled that those warnings are errors in the CI.
This PR is now switching compile warnings for GCC into compile-time errors.

### CODE REVIEW

**Comment by psychocoderHPC** [comment]
This PR can be reviewed.

**Review by sbastrakov — DISMISSED** [review]

**Comment by sbastrakov** [comment]
There is currently one warning in the CI

**Comment by psychocoderHPC** [comment]
@ComputationalRadiationPhysics/picongpu-maintainers  ready to merge

**Review by PrometheusPi — APPROVED** [review]
lgtm

**Pull request merged**
