### PR TITLE
remove forgotten unused file

### PR DESCRIPTION
**Pull request by BenjaminW3**
The traits defined in this file are not used by any code and seem to be a left-over.
I think they can be removed.

### CODE REVIEW

**Comment by PrometheusPi** [comment]
@BenjaminW3 Great you found this deprecated code :+1:

**Comment by ax3l** [comment]
again, this is not *deprecated*.

please be a bit more careful with accepting changes to parts in the code that someone else wrote. it might be worth checking the original authors or @psychocoderHPC for cross-checking.

**Comment by BenjaminW3** [comment]
I already discussed this with @psychocoderHPC offline some weeks ago and he confirmed it is deprecated.

**Comment by ax3l** [comment]
perfect, in that case all right you two! :+1:

**Comment by ax3l** [comment]
As a general community best practice: pls add the result of offline-communcation to the logs/descriptions/comment, else we cut-off people that are not sitting in the same room/lab/country/continent.

**Pull request merged**
