### PR TITLE
Adds compatibility to isaac glm PR

### PR DESCRIPTION
**Pull request by FelixTUD**
Adds compatibility to isaac glm PR with changed interface and isaac types
[https://github.com/ComputationalRadiationPhysics/isaac/pull/130](url)

[psychocoder edited] CI do not need to be updated, this PR is compatible with ISAAC 1.5.2

### CODE REVIEW

**Comment by sbastrakov** [comment]
@FelixTUD there is an issue with formatting. Please follow [these instructions](https://github.com/ComputationalRadiationPhysics/picongpu/blob/dev/docs/COMMIT.md#format-code) to reformat, or #3464 if this gets complicated

**Comment by FelixTUD** [comment]
@sbastrakov the formatting is updated now

**Comment by psychocoderHPC** [comment]
Are the changes compatible to the last isaac release? The CI is checking the dev branch of ISAAC which is equal to the last release.

**Comment by FelixTUD** [comment]
No, the isaac interface changes with the isaac pull request
https://github.com/ComputationalRadiationPhysics/isaac/pull/130
this is just the fix for it, that picongpu can use it againt, after the isaac pull request is merged

**Comment by psychocoderHPC** [comment]
I set this PR to `draft`, we need to update the CI container to have the new ISAAC version in our test and we need to check by hand that the new ISAAC version is used. The reason for the manual test is that we are not able to enforce searching for ISAAC or other optional dependancies.

**Review by psychocoderHPC — APPROVED** [review]

**Pull request merged**
