### PR TITLE
Python visualization modules

### PR DESCRIPTION
**Pull request by codingS3b**
This adds a new directory called `visualization` within the `lib/python/picongpu/` directory. 
This contains classes for displaying plots for energy histograms, phase space diagrams and pngs.
All visualization modules can also be accessed from the command line.

### CODE REVIEW

**Comment by PrometheusPi** [comment]
Great job with the visualizer. There are still some errors with the coding style. Please see travis-ci output.

**Comment by RayArdila** [comment]
sudo apt-get install git

**Comment by RayArdila** [comment]
#2479

**Comment by RayArdila** [comment]
#2479

**Pull request closed without merging**
