### PR TITLE
Docs: Fix Plugin Table

### PR DESCRIPTION
**Pull request by ax3l**
Someone broke the plugin table markdown. Fixed it.

### CODE REVIEW

**Comment by PrometheusPi** [comment]
Great fix - the table now shows up - but something strange happened to the footnotes:
grafik

**Comment by PrometheusPi** [comment]
Just es reference - the footnotes before:
grafik

**Comment by ax3l** [comment]
Dunno, seams unrelated to me.

**Comment by ax3l** [comment]
This behaviour can probably be set as an option somewhere, but do not have time to look it up right now.

**Pull request merged**
