### PR TITLE
PIConGPU use tiny RNG

### PR DESCRIPTION
**Pull request by psychocoderHPC**
- add class `RngWrapper`
- refactor template signature for particle functors/manipulator/filter with RNG
- update documentation
- MySimulation: enable always the RNG which holds the states over the full simulation
- update default param files

# Tests

- [x] default LWFA
  - LWFA is running two times faster due to faster initialization during the slide
- [x] default KHI
- [x] rebase against #2451 to solve the compile issues

### CODE REVIEW

**Comment by ax3l** [comment]
@psychocoderHPC the double-precision compile tests are not happy with your change set yet ;)

**Comment by psychocoderHPC** [comment]
:-(  The generator is currently not implemented for double. I will implement it for double too.

**Comment by psychocoderHPC** [comment]
rebase against #2451 is needed to solve the compile issues

**Comment by ax3l** [comment]
@psychocoderHPC pls rebase :)

**Pull request merged**
