### PR TITLE
Remove unused ParticlePatches class

### PR DESCRIPTION
**Pull request by sbastrakov**
This class is never used. The openPMD plugin uses patches from openPMD API.

(Unless I've missed something, but then the CI should catch it).

### CODE REVIEW

**Comment by steindev** [comment]
So, I guess, you checked that these files are nowhere included?

**Comment by sbastrakov** [comment]
Well, it's a little bit more complicated in this case. As the `.cpp` file was automatically part of the `picongpu-hostonly` library. But it seems to me that except compiling them, there is no actual use.

**Comment by steindev** [comment]
But I see it is used in struct WriteSpecies::operator(), line 531 of `include/picongpu/plugins/openpmd/WriteSpecies.hpp`. What about this?

**Comment by sbastrakov** [comment]
No, that one is from openPMD API. That is confusing, as pointed out in issue #3390

**Comment by steindev** [comment]
Then it is more a question whether this should be kept as a backup? I don't think so, as we have a versioning. And it will probably outdate at some point since we are not using it anyways.

Any objections @franzpoeschel, @psychocoderHPC?

**Review by PrometheusPi — APPROVED** [review]

**Comment by psychocoderHPC** [comment]
> Then it is more a question whether this should be kept as a backup? I don't think so, as we have a versioning. And it will probably outdate at some point since we are not using it anyways.
> 
> Any objections @franzpoeschel, @psychocoderHPC?

Maybe it is a leftover of our HDF5 pluign. But as you wrote we have versioning, so there is no need to keep this unused code.

**Review by psychocoderHPC — APPROVED** [review]

**Pull request merged**
