### PR TITLE
fix copyright notice

### PR DESCRIPTION
**Pull request by BrianMarre**
fixes the erroneous copyright comment described in #4841, with consent of the original author given in the issue thread.

### CODE REVIEW

**Comment by psychocoderHPC** [comment]
CI is failing because https://pypi.org/ is to slow and the install is running into timeouts.
Maybe we have a local network issue in our research center.

**Comment by BrianMarre** [comment]
@psychocoderHPC ready for review

**Review by ikbuibui — APPROVED** [review]
Looks fine. Also silently fixes the double space before `See the` in line 12 here, which is present in other headers in PIConGPU.

**Comment by BrianMarre** [comment]
Oops did not do that on purpose, just copied it from somewhere else.

**Comment by BrianMarre** [comment]
@ikbuibui I create a second PR, #4847, to fix this doubled space in all pmacc and picongpu files

**Review by psychocoderHPC — APPROVED** [review]

**Pull request merged**
