### PR TITLE
fix SynchrotronRadiation

### PR DESCRIPTION
**Pull request by psychocoderHPC**
**IMPORTANT** Due to the bug fixed in this PR the current dev is not usable.

Fix  that the current dev is always failing with
```
terminate called after throwing an instance of 'char const*'
```
due to wrong usage of `throw`.
The second issue is that the stage is always consuming memory and is performing initializing helper fields based on the default param input. This is one reason why the first issue was showing even if the synchrotron extension is not activated.

Bug was introduced with #4827

### CODE REVIEW

**Comment by psychocoderHPC** [comment]
@PrometheusPi @FilipO28555 please check the default parameters in our synchrotron.param file because if we use these will will get the error

```
[1,0]<stdout>:Caught exception when precomputing firstSynchrotronFunction at 1192. index: SynchrotronRadiation.hpp: integrateAsExponential(): yLeft and yMiddle must be positive.

```

**Review by PrometheusPi — APPROVED** [review]

**Comment by PrometheusPi** [comment]
When running the Synchrotron test, I get: 
```
﻿﻿calculation  simulation time:  1min  4sec 925msec = 64.925 sec
full simulation time:  1min 22sec 135msec = 82.135 sec
Validate!
PIConGPU prefix = ...PIConGPU/_pr_4923/picongpu/
Load buildsystem/CompileSuite/color.sh from PIConGPU!
Execute validate.py with data from ...PIConGPU/_pr_4923/projects/Synchrotron/simOutput
Validating data in ...PIConGPU/_pr_4923/projects/Synchrotron/simOutput
/trinity/shared/pkg/devel/python/3.10.4/lib/python3.10/site-packages/scipy/integrate/_quadpack_py.py:463: ComplexWarning: Casting complex values to real discards the imaginary part
  return _quadpack._qagse(func,a,b,args,full_output,epsabs,epsrel,limit)
...PIConGPU/_pr_4923/projects/Synchrotron/./lib/validate.py:98: IntegrationWarning: The occurrence of roundoff error is detected, which prevents
  the requested tolerance from being achieved.  The error may be
  underestimated.
  analytical_integrated.append(quad(lambda x: analytical_Propability(x, gamma, Heff, dt), x0, x1)[0])
Poorness: 1428967203.6987355
[testSuite] Synchrotron radiation plugin has bad performance!
[testSuite] Check Synchrotron plugin implementation!

```

**Comment by PrometheusPi** [comment]
The failing synchrotron run time test will be fixed after this pull request.

**Comment by PrometheusPi** [comment]
Both the synchrotron test and the LWFA example run fine. (Only the check of the synchrotron test fails.)

**Pull request merged**
