### PR TITLE
create E and B field from moving particles

### PR DESCRIPTION
**Pull request by psychocoderHPC**
Allow creating the E and B field based on initialized moving particles current.

- [ ] Currently, a draft to check if we need to add ISimulationData to more field solver implementations.

### CODE REVIEW

**Comment by psychocoderHPC** [comment]
@PrometheusPi We should discuss how we should go on with this PR.

**Comment by PrometheusPi** [comment]
@psychocoderHPC If I load my particles from a checkpoint, I cannot apply the new method, right?

**Comment by psychocoderHPC** [comment]
I will close this PR because this PR is only producing the current from a warm plasma and propagating the field's N steps.
The concepts will be used in another upcoming feature by one of our students.

**Comment by psychocoderHPC** [comment]
I reopened this PR because I need to port `ExecuteIfTimeStepEq` to our code base, these are useful objects for our particle init pipe and the per timestep pipe.

**Comment by psychocoderHPC** [comment]
time dependent functor execution is moved out to PR #4934

**Pull request closed without merging**
