### PR TITLE
Particle thinning plugin with reduction library prototype

### PR DESCRIPTION
**Pull request by KseniaBastrakova**
PIConGPU particle merger plugin, that uses reduction C++ library.
We define  traits for particles' values acess and run "in kernell" version of algorithm

### CODE REVIEW

**Comment by KseniaBastrakova** [comment]
expected_actual

**Comment by psychocoderHPC** [comment]
Please do jot forget the documentation (rst files) for the plugin and if this Plugin requires an optional dependency for PIConGPU add the dependency to the coresponding documentation too.

**Comment by psychocoderHPC** [comment]
Let us talk next week about secure integration onto the PIConGPU event system to avoid data races.

**Comment by psychocoderHPC** [comment]
@sbastrakov We should talk about this PR in person.

**Comment by sbastrakov** [comment]
I think practically speaking we should close this PR. If we need such reduction in PIConGPU, we can just implement one of those algorithms on our side and not have that external dependency that no one supports anymore.

**Pull request closed without merging**
