### PR TITLE
ADIOS install instructions for ArchLinux

### PR DESCRIPTION
**Pull request by slizzered**
- I created an AUR package for ADIOS: https://aur4.archlinux.org/packages/libadios/

### CODE REVIEW

**Comment by bussmann** [comment]
Will you forward this to the ADIOS project?

**Comment by slizzered** [comment]
I believe packaging is distribution-specific and of no real interest to the ADIOS project itself. So no, I did not intend to forward this. Unless there is a huge demand in the ArchLinux community AND one of the *Trusted Users* feels like pulling this package into the official repositories, there is nothing left to do for us here.

**Comment by ax3l** [comment]
good idea. what about ;)

@pnorbert hi norbert, just a side note: since adios was not yet in the repositories of ArchLinux, a student of us took the time and uploaded the latest release to the `AUR` repositories (untrusted, contributed user packages; similar to the PPA repos in Ubuntu) under https://aur4.archlinux.org/packages/libadios/ .
In case someone needs it from your user base, we documented the usage in our install guide lines https://github.com/ComputationalRadiationPhysics/picongpu/blob/dev/doc/INSTALL.md#optional-libraries Default transformations are enabled but extra transports such as netcdf and phdf5 are not.

**Comment by ax3l** [comment]
@slizzered thanks a lot, that is great!

**Comment by ax3l** [comment]
@slizzered in your aur package, `netcdf` still seems to be a dependency?

**Comment by slizzered** [comment]
@ax3l  yes, I don't have the required SSH-key with me right now, so I can not update the PKGBUILD until I get to my other computer ;)

**Pull request merged**
