### PR TITLE
Examples: Collisional Ionization Include

### PR DESCRIPTION
**Pull request by ax3l**
Adds the include in `speciesDefiniton.param` to examples where it was still missing. Otherwise Thomas-Fermi ionization could not be used in the `ionizers< ... >` sequence.

### CODE REVIEW

**Comment by psychocoderHPC** [comment]
#2040 fix is solving a missing include which could be related to this PR.

**Comment by ax3l** [comment]
imo, #2040 is not related to this PR. This PR is purely about having a class `::ThomasFermi` as forward define available in `speciesDefinition.param`

**Comment by ax3l** [comment]
ionizers.def only contains data tables and no algorithms, but as long as it is included before `speciesDefinition` we could in principle also put the includes there, although they are not used there.

a cleaner way would be to hide those from the user completely and add such forward defines in the loader

**Comment by psychocoderHPC** [comment]
@ax3l  I created an pull request to your PR to move the includes out of speciesDefinition.param

**Comment by ax3l** [comment]
@psychocoderHPC thanks, applied your PR!

**Pull request merged**
