### PR TITLE
Release 0.5.0

### PR DESCRIPTION
**Pull request by psychocoderHPC**
Merge release branch to master for the today's PIConGPU release

### CODE REVIEW

**Comment by sbastrakov** [comment]
@psychocoderHPC looks like cupla got some issues with the build, at least for gcc 5, do you have an idea?

**Comment by sbastrakov** [comment]
Ah, it may be the same as in #3254?

**Comment by psychocoderHPC** [comment]
I will do a manuell compile test on hemera and/or fwk394 (CUDA)

**Comment by psychocoderHPC** [comment]
I compiled all on fwk394. My tests on hemera running into the walltime. Only k20 is free and compiling there takes ages.

Feel free to merge.

**Comment by psychocoderHPC** [comment]
I switched the CI back to the old modules. I feel somehow bad to do not see passed CI tests for a release.

**Comment by PrometheusPi** [comment]
@psychocoderHPC still waiting for the compile suite to finish ...

**Comment by PrometheusPi** [comment]
@psychocoderHPC I have merged the `release-0.5.0` into the master. You can now start the publishing process. Please wait until at least 22:10 CEST until you update the compile suite (otherwise there will be warnings of a non-compiling master branch).

**Comment by psychocoderHPC** [comment]
- PIConGPU is relesed
- the CI is switched back to the new modules for C++14
- before we announce the release https://github.com/ComputationalRadiationPhysics/spack-repo/pull/7 must be merged (@ax3l is aware )

**Pull request merged**
