### PR TITLE
Fix inaccuracies in incident field solver

### PR DESCRIPTION
**Pull request by sbastrakov**
As discovered by Max ~~(student of @steindev , doesn't have a github account)~~ @Enderpigmen there were some inaccuracies in the incident field solver implementation. It was still working, but produced more "noise" and inaccuracies than it should have. It was missed previously as the functors I used for testing were a bit unfortunately chosen and couldn't show it. The two commits are two unrelated fixes.

Draft while waiting for Max to check it on all directions, for now he did with Y (as we originally saw issues there). Thanks to him for running lots of simulations and demonstrating the problem!

### CODE REVIEW

**Comment by sbastrakov** [comment]
Oh, now there is an account @Enderpigmen

**Comment by PrometheusPi** [comment]
Great catch @Enderpigmen - thanks for such a quick fix @sbastrakov

**Comment by Enderpigmen** [comment]
I checked the incident Field Method with the fix and pure Plane Waves and it works now from all directions ( when the source is either applied at XMin, XMax, ...).

**Comment by Enderpigmen** [comment]
Here is the issue in the electrical field of a plane wave starting from YMin before the fix:

Incident Field before

and after the fix


Incident Field after

**Review by psychocoderHPC — APPROVED** [review]

**Pull request merged**
