### PR TITLE
crusher-ornl: Remove `--mpiDirect` due to resulting MPI errors

### PR DESCRIPTION
**Pull request by steindev**

### CODE REVIEW

**Comment by steindev** [comment]
Do not merge yet. Maybe we just forgot to set an environment variable. I am investigating.

**Comment by psychocoderHPC** [comment]
I converted this PR to a draft that it does not get accidentally merged.

**Comment by sbastrakov** [comment]
What's the status of this PR?

**Comment by steindev** [comment]
We set the required environment variable in `batch.profile`. It seems, `--mpiDirect` just does not work. I forgot my dongle today, but will check tomorrow with my crashing simulation again and also try with a KHI

**Comment by steindev** [comment]
Update: GPU's firmware update was updated 2 days ago. The update is supposed to fix errors with `--mpiDirect`.
KHI works on 64 nodes as of yesterday.
Even when using 25GiB GPU memory.
I close this PR in hope the issues are resolved.

**Pull request closed without merging**
