### PR TITLE
Fix: Remove rendundant comma in speciesDefinition.param

### PR DESCRIPTION
**Pull request by n01r**
Removes a rendundant comma that was left over from a temporary change in the parameter file.

### CODE REVIEW

**Comment by n01r** [comment]
I feel that we are being overly ironic in our reviews :wink:

**Comment by theZiz** [comment]
[mimi muppet](http://www.youtube.com/watch?v=kV4vHpqrj6E "mimi muppet ")

**Comment by n01r** [comment]
really lovely :heart:

**Comment by n01r** [comment]
Dude, merge me!

**Pull request merged**
