### PR TITLE
C Includes Examples: Fix Correct C++ Style

### PR DESCRIPTION
**Pull request by ax3l**
Fix all `cassert` (RT assert) includes in PIConGPU examples to use correct [C++ include style](https://en.wikipedia.org/wiki/C%2B%2B_Standard_Library#C_standard_library) instead of C-style.

### CODE REVIEW

**Comment by PrometheusPi** [comment]
Could you add your name to the license header (of the last file).

**Comment by PrometheusPi** [comment]
The rest looks great.

**Comment by ax3l** [comment]
updated

**Comment by PrometheusPi** [comment]
@ax3l great :+1:

**Pull request merged**
