### PR TITLE
`laserConfig.param`: Remove Confusing Comments

### PR DESCRIPTION
**Pull request by ax3l**
Remove confusing comments from `laserConfig.param`. (Reported a user on the mailing list.)

### CODE REVIEW

**Comment by PrometheusPi** [comment]
Please remove the following comments too:
in ` examples/Bunch/include/simulation_defines/param/laserConfig.param `:
```c++
// line 221:
 BOOST_CONSTEXPR_OR_CONST float_64 LASER_NOFOCUS_CONSTANT_SI = 7.0 * WAVE_LENGTH_SI / ::picongpu::SI::SPEED_OF_LIGHT_SI; //0.0;//50.0e-15;
```

in ` examples/LaserWakefield/include/simulation_defines/param/laserConfig.param `:
```c++
// line 167:
 BOOST_CONSTEXPR_OR_CONST float_64 LASER_NOFOCUS_CONSTANT_SI = 13.34e-15; //7.0*WAVE_LENGTH_SI/::picongpu::SI::SPEED_OF_LIGHT_SI;//13.34e-15;//25.0e-15;

// line 181:
 BOOST_CONSTEXPR_OR_CONST float_64 RAMP_INIT = 20.6146; //25.6415;//SI::aux_calulation::PULSE_TIME_SI/SI::PULSE_LENGTH_SI;

// line 221:
 BOOST_CONSTEXPR_OR_CONST float_64 LASER_NOFOCUS_CONSTANT_SI = 7.0 * WAVE_LENGTH_SI / ::picongpu::SI::SPEED_OF_LIGHT_SI; //0.0;//50.0e-15;
```

in ` examples/SingleParticleRadiationWithLaser/include/simulation_defines/param/laserConfig.param `:
```c++
// line 176:
 BOOST_CONSTEXPR_OR_CONST float_64 LASER_NOFOCUS_CONSTANT_SI = /*13.34e-15;*/6.0 * WAVE_LENGTH_SI / ::picongpu::SI::SPEED_OF_LIGHT_SI; //13.34e-15;//25.0e-15;

// line 190:
 BOOST_CONSTEXPR_OR_CONST float_64 RAMP_INIT = 20.6146; //25.6415;//SI::aux_calulation::PULSE_TIME_SI/SI::PULSE_LENGTH_SI;

// line 230:
 BOOST_CONSTEXPR_OR_CONST float_64 LASER_NOFOCUS_CONSTANT_SI = 7.0 * WAVE_LENGTH_SI / ::picongpu::SI::SPEED_OF_LIGHT_SI; //0.0;//50.0e-15;
```

in ` src/picongpu/include/simulation_defines/param/laserConfig.param `:
```c++
// line 167:
 BOOST_CONSTEXPR_OR_CONST float_64 LASER_NOFOCUS_CONSTANT_SI = 13.34e-15; //7.0*WAVE_LENGTH_SI/::picongpu::SI::SPEED_OF_LIGHT_SI;//13.34e-15;//25.0e-15;

// line 181:
 BOOST_CONSTEXPR_OR_CONST float_64 RAMP_INIT = 20.6146; //25.6415;//SI::aux_calulation::PULSE_TIME_SI/SI::PULSE_LENGTH_SI;

// line 221:
 BOOST_CONSTEXPR_OR_CONST float_64 LASER_NOFOCUS_CONSTANT_SI = 7.0 * WAVE_LENGTH_SI / ::picongpu::SI::SPEED_OF_LIGHT_SI; //0.0;//50.0e-15;
```

I think these are all, but please check again.

Please also state, that you rewrote some of the numerical values, but they quantitatively stayed the same.

**Comment by ax3l** [comment]
removed and found one more.

**Comment by PrometheusPi** [comment]
You missed ` examples/SingleParticleRadiationWithLaser/include/simulation_defines/param/laserConfig.param` line 176 (very long line of code)

**Comment by PrometheusPi** [comment]
Great you found another confusing comment :+1:

Please squash your commits to a single commit.

**Comment by bussmann** [comment]
There should be an ice cream reward for this!

**Comment by ax3l** [comment]
Are we talking :ice_cream: , :icecream: or shaved ice :shaved_ice: ?

Updated & squashed.

**Comment by PrometheusPi** [comment]
@ax3l thx. I will merge as soon as all compile test are done. 

(We are talking about 🌵! )

**Pull request merged**
