### PR TITLE
add both adios and adios2 module on hemera

### PR DESCRIPTION
**Pull request by PrometheusPi**
This pull request solves the issue #3409. The IT department separated the adios modules to an adios and and an adios2 base module. Both adios(1) and adios2 can thus be loaded in parallel.

### CODE REVIEW

**Review by sbastrakov — APPROVED** [review]
Thanks!

This is not really related, but also concerns ADIOS on Hemera: do they still have only modules for CUDA?

**Review by steindev — APPROVED** [review]

**Comment by pordyna** [comment]
```
Lmod has detected the following error:  Cannot load module "openpmd/0.12.0-cuda102" without
these module(s) loaded:
   adios/2.6.0-cuda102
```
It looks like the dependencies weren't updated after switching the module name to adios2. I have started a ticket with our IT Helpdesk.

**Comment by steindev** [comment]
> ```
> Lmod has detected the following error:  Cannot load module "openpmd/0.12.0-cuda102" without
> these module(s) loaded:
>    adios/2.6.0-cuda102
> ```
> 
> It looks like the dependencies weren't updated after switching the module name to adios2. I have started a ticket with our IT Helpdesk.

Uhh I just tried to load the adios and adios2 module half an hour ago. But I didn't test the `openPMD` module... :roll_eyes:

**Comment by pordyna** [comment]
So It should be fixed now. The CI failed but it looks like it was just some network error? Maybe we just need to restart it.

**Comment by steindev** [comment]
Indeed, I can confirm that it works now as expected.

Regarding the CI, Richard needs to `git commit --amend; git push -f` in order to start the CI again with a new push (that actually changes nothing in the code base)

**Comment by PrometheusPi** [comment]
@steindev I re-triggered the CI as you suggested.

**Review by steindev — APPROVED** [review]

**Pull request merged**
