### PR TITLE
CI: latest container v1.1

### PR DESCRIPTION
**Pull request by psychocoderHPC**
- switch to conatiner v1.1
- activate ISAAC 1.6.0-dev tests
- fix silently disabled openPMD tests

ISAAC code should now be fixed to be able to compile together with PIConGPU.

### CODE REVIEW

**Comment by sbastrakov** [comment]
@psychocoderHPC there are some issues in CI, and it looks like caused by your changes in this PR

**Comment by psychocoderHPC** [comment]
> @psychocoderHPC there are some issues in CI, and it looks like caused by your changes in this PR

Yes, the names of the containers are slightly different between cuda versions and non-cuda version.
Fix is on the way.

**Comment by psychocoderHPC** [comment]
I opened issue #3473 to avoid silently disabled features. One problem which is fixed together with the PR.

**Comment by psychocoderHPC** [comment]
ready

**Review by sbastrakov — APPROVED** [review]

**Pull request merged**
