### PR TITLE
remove titan ornl setup and doc

### PR DESCRIPTION
**Pull request by PrometheusPi**
Since [2019-08-02 the Titan system at ORNL is decommissioned](https://www.olcf.ornl.gov/olcf-resources/compute-systems/titan/). This pull request removes all references to and setups for this cluster in the current `dev` to clean up our documentation and setup directory .

If you want to see the setup of this system, please refer to a previous version of PIConGPU. 

(The outdated documentation showed up as part of the research for issue #3085.)

### CODE REVIEW

**Comment by PrometheusPi** [comment]
@sbastrakov Thanks for pointing this out - I didn't know this workaround - perhaps @psychocoderHPC or @ax3l know more - but I agree, if it is not certain it is only effecting Titan, we should keep it.

**Comment by ax3l** [comment]
That workaround was only for tracing. Can probably go.

**Comment by psychocoderHPC** [comment]
RIP :cry:

**Comment by PrometheusPi** [comment]
@ax3l Okay - I will remove it.

**Pull request merged**
