### PR TITLE
update to alpaka pre-0.4.0 version

### PR DESCRIPTION
**Pull request by psychocoderHPC**
updated version of #2807 to verify issues before we release a new alpaka version

update Cupla from :https://github.com/ComputationalRadiationPhysics/cupla/commit/73fb269a8c080e613b0abe860f5d101ba1107e1d to https://github.com/ComputationalRadiationPhysics/cupla/commit/a96b293dcb14662a57901b55dfedaa1cd615adc9

```
GIT_AUTHOR_NAME="Third Party" GIT_AUTHOR_EMAIL="picongpu@hzdr.de" git subtree pull --prefix thirdParty/cupla/ git@github.com:ComputationalRadiationPhysics/cupla.git dev --squash
```

update alpaka from https://github.com/ComputationalRadiationPhysics/alpaka/commit/b5c66c2a48e097e06bf1c69fb2c83b99d96d70b0 to https://github.com/ComputationalRadiationPhysics/alpaka/commit/6b42f89204a6800a926b36f07d8fd2908892378e

```
GIT_AUTHOR_NAME="Third Party" GIT_AUTHOR_EMAIL="picongpu@hzdr.de" \
  git subtree pull --prefix thirdParty/alpaka \                                                  
  git@github.com:ComputationalRadiationPhysics/alpaka.git develop --squash
```

### CODE REVIEW

**Comment by psychocoderHPC** [comment]
@ax3l Do you see why the CI is not checking my PR. I have currently no access to the CI node and can not check it by myself :-(

**Comment by psychocoderHPC** [comment]
We need to check the cmake version of our CI because travis is also showing that we are using an to old cmake https://travis-ci.org/ComputationalRadiationPhysics/picongpu/jobs/530345749#L812

**Comment by psychocoderHPC** [comment]
Note: The problem why the CI is not showing any error is that the error log is 12MiB and this is too large.
In general local tests show that we still have the issue with cuda8 and this PR what we already observed in #2807.
We need to switch to CUDA 9.X for this PR. Some examples still run with CUDA8 so we should not forbit the usage but should remove support for this version.

**Comment by ax3l** [comment]
That's ok with me to got for cuda 9+ with PIConGPU 0.5.0/1.0.0

On May 10, 2019 2:06:32 PM GMT+02:00, "René Widera" <notifications@github.com> wrote:
>Note: The problem why the CI is not showing any error is that the error
>log is 12MiB and this is too large.
>In general local tests show that we still have the issue with cuda8 and
>this PR what we already observed in #2807.
>We need to switch to CUDA 9.X for this PR. Some examples still run with
>CUDA8 so we should not forbit the usage but should remove support for
>this version.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/ComputationalRadiationPhysics/picongpu/pull/2958#issuecomment-491265557

--
Sent from my smartphone.
Please excuse my brevity.

**Comment by psychocoderHPC** [comment]
Since the CI is not showing the full error I run the test manually on the CI node:

```
In file included from /tmp/tmpxft_00006220_00000000-5_main.cudafe1.stub.c:5:0,
                 from tmpxft_00006220_00000000-5_main.cudafe1.stub.c:1:
/tmp/tmpxft_00006220_00000000-5_main.cudafe1.stub.c: In function ‘void __device_stub__ZN6alpaka6kernel4cuda6detail10cudaKernelISt17integral_constantImLm3EEjN5cupla16cupla_cuda_async11CuplaKernelIN8picongpu21KernelEnergyParticlesILj256EEEEEJN5pmacc12ParticlesBoxINSD_5FrameINSD_15ParticlesBufferINSD_19ParticleDescriptionINSD_11compileTime6StringIJLc101ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0EEEENSD_4math2CT6VectorIN4mpl_10integral_cIiLi8EEESQ_NSP_IiLi4EEEEEN5boost3mpl6v_itemINS9_24placeholder_definition309weightingENSV_INS9_24placeholder_definition288momentumENSV_INS9_24placeholder_definition258positionINS9_24placeholder_definition2712position_picENSD_24placeholder_definition2213pmacc_isAliasEEENSU_7vector0INSO_2naEEELi0EEELi0EEELi0EEENSV_INS9_24placeholder_definition5111chargeRatioINS9_25placeholder_definition13120ChargeRatioElectronsES15_EENSV_INS9_24placeholder_definition509massRatioINS9_25placeholder_definition13018MassRatioElectronsES15_EENSV_INS9_24placeholder_definition467currentINS9_13currentSolver9EsirkepovINS9_9particles6shapes3CICELj3EEES15_EENSV_INS9_24placeholder_definition4513interpolationINS9_28FieldToParticleInterpolationIS1T_NS9_30AssignedTrilinearInterpolationEEES15_EENSV_INS9_24placeholder_definition385shapeIS1T_S15_EENSV_INS9_24placeholder_definition3914particlePusherINS1R_6pusher5BorisES15_EES19_Li0EEELi0EEELi0EEELi0EEELi0EEELi0EEENSD_17HandleGuardRegionINSD_9particles8policies17ExchangeParticlesENS1R_8boundary29CallPluginsAndDeleteParticlesEEES19_S19_EESS_N8mallocMC9AllocatorINS2O_16CreationPolicies7ScatterINS9_16DeviceHeapConfigENS2Q_11ScatterConf27DefaultScatterHashingParamsEEENS2O_20DistributionPolicies4NoopENS2O_11OOMPolicies10ReturnNullENS2O_19ReservePoolPolicies16SimpleCudaMallocENS2O_17AlignmentPolicies6ShrinkINS32_12ShrinkConfig19DefaultShrinkConfigEEEEELj3EE29OperatorCreatePairStaticArrayILj256EEENSH_ISK_SS_NSV_INSD_24placeholder_definition249multiMaskENSV_INSD_24placeholder_definition2312localCellIdxES1C_Li0EEELi0EEES2F_S2M_S19_NSV_INSD_12NextFramePtrINSO_3argILi1EEEEENSV_INSD_16PreviousFramePtrIS3J_EES19_Li0EEELi0EEEEEEENS2O_19AllocatorHandleImplIS37_EELj3EEENSD_7DataBoxINSD_10PitchedBoxIdLj1EEEEENSD_11AreaMappingILj3ENSD_18MappingDescriptionILj3ESS_EEEENSD_7functor9InterfaceINS1R_6filter3AllELj1EbEEEEEvNS_3vec3VecIT_T0_EET1_DpT2_(const _ZN6alpaka3vec3VecISt17integral_constantImLm3EEjEE&, const _ZN5cupla16cupla_cuda_async11CuplaKernelIN8picongpu21KernelEnergyParticlesILj256EEEEE&, _ZN5pmacc13ParticlesBaseINS_19ParticleDescriptionINS_11compileTime6StringIJLc101ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0EEEENS_4math2CT6VectorIN4mpl_10integral_cIiLi8EEESA_NS9_IiLi4EEEEEN5boost3mpl6v_itemIN8picongpu24placeholder_definition309weightingENSF_INSG_24placeholder_definition288momentumENSF_INSG_24placeholder_definition258positionINSG_24placeholder_definition2712position_picENS_24placeholder_definition2213pmacc_isAliasEEENSE_7vector0INS8_2naEEELi0EEELi0EEELi0EEENSF_INSG_24placeholder_definition5111chargeRatioINSG_25placeholder_definition13120ChargeRatioElectronsESQ_EENSF_INSG_24placeholder_definition509massRatioINSG_25placeholder_definition13018MassRatioElectronsESQ_EENSF_INSG_24placeholder_definition467currentINSG_13currentSolver9EsirkepovINSG_9particles6shapes3CICELj3EEESQ_EENSF_INSG_24placeholder_definition4513interpolationINSG_28FieldToParticleInterpolationIS1E_NSG_30AssignedTrilinearInterpolationEEESQ_EENSF_INSG_24placeholder_definition385shapeIS1E_SQ_EENSF_INSG_24placeholder_definition3914particlePusherINS1C_6pusher5BorisESQ_EESU_Li0EEELi0EEELi0EEELi0EEELi0EEELi0EEENS_17HandleGuardRegionINS_9particles8policies17ExchangeParticlesENS1C_8boundary29CallPluginsAndDeleteParticlesEEESU_SU_EENS_18MappingDescriptionILj3ESC_EEN8mallocMC9AllocatorINS2B_16CreationPolicies7ScatterINSG_16DeviceHeapConfigENS2D_11ScatterConf27DefaultScatterHashingParamsEEENS2B_20DistributionPolicies4NoopENS2B_11OOMPolicies10ReturnNullENS2B_19ReservePoolPolicies16SimpleCudaMallocENS2B_17AlignmentPolicies6ShrinkINS2P_12ShrinkConfig19DefaultShrinkConfigEEEEEE16ParticlesBoxTypeE&, _ZN5pmacc7DataBoxINS_10PitchedBoxIdLj1EEEEE&, _ZN5pmacc11AreaMappingILj3ENS_18MappingDescriptionILj3ENS_4math2CT6VectorIN4mpl_10integral_cIiLi8EEES7_NS6_IiLi4EEEEEEEEE&, _ZNSt3_MuISt12_PlaceholderILi1EELb0ELb1EE6resultIFS2_S1_St5tupleIJN5pmacc7functor9InterfaceIN8picongpu9particles6filter3AllELj1EbEEEEEE11__base_typeE&)’:
/tmp/tmpxft_00006220_00000000-5_main.cudafe1.stub.c:995:4921: error: invalid application of ‘sizeof’ to incomplete type ‘_ZNSt3_MuISt12_PlaceholderILi1EELb0ELb1EE6resultIFS2_S1_St5tupleIJN5pmacc7functor9InterfaceIN8picongpu9particles6filter3AllELj1EbEEEEEE11__base_typeE {aka _ZN5pmacc7functor9InterfaceIN8picongpu9particles6filter3AllELj1EbEE}’
```

**Comment by psychocoderHPC** [comment]
Test faile with CUDA 9.0 and 9.1. :-(
CUDA 9.2 works fine.

**Comment by psychocoderHPC** [comment]
Tested CUDA 10.1: compile without issues

```bash
 ...........,_
 ........../.(|
 ..........\..\ 
 ........___\..\,. ~~~~~~
 .......(__)_)...\ 
 ......(__)__)|...|
 ......(__)__)|.__|
 .......(__)__)___/~~~~~~
```

**Comment by psychocoderHPC** [comment]
@ax3l As discussed please merge this PR as it is even if we not update directly to the latest version of alpaka and cupla. Do to the renamings in the libraries there was some hand work needed to solve merge conflicts (I checked my changes against a clean checkout of the corresponding library)

**Comment by ax3l** [comment]
CI and project updated to only support CUDA 9.2 or newer in #2975

**Pull request merged**
