### PR TITLE
TBG: Add Defaults via Env for -s|-t

### PR DESCRIPTION
**Pull request by ax3l**
This feature shortens the `tbg` call dramatically without harming its generality.

The `-s | --submit` option is the batch system and unique for each machine. That is a perfect candidate for a `picongpu.profile` or a general `.profile` setting (as a default).

The `-t | --tpl` file is useful if you have various queues or debug templates. 99% of the users always submit to the same queue and would love a default, too. Developers or power users with varying queues can still use `-t` to overwrite the default.

If `TBG_SUBMIT` or `TBG_TPLFILE` are not set, the default values are still `""` which will result in a standard error from `tbg`.

### CODE REVIEW

**Comment by ax3l** [comment]
Actually, flags with [optional arguments](https://stackoverflow.com/questions/11517139/optional-option-argument-with-getopts) seem hackable in `getopts`.

**Comment by psychocoderHPC** [comment]
With `getopts` it is not possible :-( 
If we found no clean solution up to middle of the next week I will accept your pull request. Even though I do not like that.

**Comment by psychocoderHPC** [comment]
@ax3l I wrote a small parser to support the explicit option syntax with the fall back to the environment variables. 
I pushed it to your pull request.

**Comment by ax3l** [comment]
Cool, I will check that on Monday.
Did you read the link I provided in my last comment?

**Comment by psychocoderHPC** [comment]
Yes I read both and found no parser. I will ckeck the links again.
I does a mistake in my previous comments, we use `getopt` and not `getopts`. `getopts`  not support long options. It might be that `getopts` is not the right tool for use.

**Comment by ax3l** [comment]
-> waiting for pull on this branch.

**Pull request merged**
