### PR TITLE
update pizdaint batch system templates

### PR DESCRIPTION
**Pull request by psychocoderHPC**
add batch system changes from 2016/06
  - remove `aprun` with `srun`
  - add flag `--gres`, `--cpus-per-task`
  - change usage of `--ntasks-per-node` (know real tasks per node)
  - update SLURM tutorial
  - update `picongpu.profile.example`

### CODE REVIEW

**Comment by ax3l** [comment]
all right, than you!

Link to documentation: http://user.cscs.ch/getting_started/running_jobs/piz_daint/index.html

**Comment by ax3l** [comment]
@psychocoderHPC can you please update the `picongpu.profile.example`, too?

- `getInteractive` script needs update with `gres`, ...

**Comment by psychocoderHPC** [comment]
updated

**Comment by ax3l** [comment]
thank you!

**Pull request merged**
