### PR TITLE
update toml11 to v3.7.1

### LINKED ISSUE #4620: compiler warning if using gcc-12
The LaserWakefield example gives me a compiler warning if I use gcc-12
```
In file included from /opt/spack-modules/linux-ubuntu20.04-skylake_avx512/gcc-10.2.0/gcc-12.2.0-nupdqwabpymog72rxix6bong2zqyms6a/lib/gcc/x86_64-pc-linux-gnu/12.2.0/../../../../include/c++/12.2.0/x86_64-pc-linux-gnu/bits/c++allocator.h:33,
                 from /opt/spack-modules/linux-ubuntu20.04-skylake_avx512/gcc-10.2.0/gcc-12.2.0-nupdqwabpymog72rxix6bong2zqyms6a/lib/gcc/x86_64-pc-linux-gnu/12.2.0/../../../../include/c++/12.2.0/bits/allocator.h:46,
                 from /opt/spack-modules/linux-ubuntu20.04-skylake_avx512/gcc-10.2.0/gcc-12.2.0-nupdqwabpymog72rxix6bong2zqyms6a/lib/gcc/x86_64-pc-linux-gnu/12.2.0/../../../../include/c++/12.2.0/string:41,
                 from /home/marre55/picongpu/include/picongpu/../picongpu/plugins/openPMD/Parameters.hpp:3,
                 from /home/marre55/picongpu/include/picongpu/../picongpu/plugins/openPMD/toml.hpp:22,
                 from /home/marre55/picongpu/include/picongpu/plugins/openPMD/toml.cpp:22:
In member function 'void std::__new_allocator<_Tp>::deallocate(_Tp*, size_type) [with _Tp = char]',
    inlined from 'static void std::allocator_traits<std::allocator<_CharT> >::deallocate(allocator_type&, pointer, size_type) [with _Tp = char]' at /opt/spack-modules/linux-ubuntu20.04-skylake_avx512/gcc-10.2.0/gcc-12.2.0-nupdqwabpymog72rxix6bong2zqyms6a/lib/gcc/x86_64-pc-linux-gnu/12.2.0/../../../../include/c++/12.2.0/bits/alloc_traits.h:496:23,
    inlined from 'void std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::_M_destroy(size_type) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]' at /opt/spack-modules/linux-ubuntu20.04-skylake_avx512/gcc-10.2.0/gcc-12.2.0-nupdqwabpymog72rxix6bong2zqyms6a/lib/gcc/x86_64-pc-linux-gnu/12.2.0/../../../../include/c++/12.2.0/bits/basic_string.h:292:34,
    inlined from 'void std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::_M_dispose() [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]' at /opt/spack-modules/linux-ubuntu20.04-skylake_avx512/gcc-10.2.0/gcc-12.2.0-nupdqwabpymog72rxix6bong2zqyms6a/lib/gcc/x86_64-pc-linux-gnu/12.2.0/../../../../include/c++/12.2.0/bits/basic_string.h:286:14,
    inlined from 'std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::~basic_string() [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]' at /opt/spack-modules/linux-ubuntu20.04-skylake_avx512/gcc-10.2.0/gcc-12.2.0-nupdqwabpymog72rxix6bong2zqyms6a/lib/gcc/x86_64-pc-linux-gnu/12.2.0/../../../../include/c++/12.2.0/bits/basic_string.h:795:19,
    inlined from 'toml::success<T>::~success() [with T = std::__cxx11::basic_string<char>]' at /home/marre55/picongpu/thirdParty/toml11/toml/result.hpp:40:5,
    inlined from 'void toml::result<T, E>::cleanup() [with T = std::__cxx11::basic_string<char>; E = std::__cxx11::basic_string<char>]' at /home/marre55/picongpu/thirdParty/toml11/toml/result.hpp:656:51,
    inlined from 'void toml::result<T, E>::cleanup() [with T = std::unordered_map<std::__cxx11::basic_string<char>, toml::basic_value<toml::discard_comments, std::unordered_map, std::vector> >; E = std::__cxx11::basic_string<char>]' at /home/marre55/picongpu/thirdParty/toml11/toml/result.hpp:654:10,
    inlined from 'toml::result<T, E>::~result() [with T = std::unordered_map<std::__cxx11::basic_string<char>, toml::basic_value<toml::discard_comments, std::unordered_map, std::vector> >; E = std::__cxx11::basic_string<char>]' at /home/marre55/picongpu/thirdParty/toml11/toml/result.hpp:244:38,
    inlined from 'toml::result<Value, std::__cxx11::basic_string<char> > toml::detail::parse_toml_file(location&) [with Value = toml::basic_value<toml::discard_comments, std::unordered_map, std::vector>]' at /home/marre55/picongpu/thirdParty/toml11/toml/parser.hpp:2127:5:
/opt/spack-modules/linux-ubuntu20.04-skylake_avx512/gcc-10.2.0/gcc-12.2.0-nupdqwabpymog72rxix6bong2zqyms6a/lib/gcc/x86_64-pc-linux-gnu/12.2.0/../../../../include/c++/12.2.0/bits/new_allocator.h:158:33: warning: 'void operator delete(void*, std::size_t)' called on unallocated object 'tab' [-Wfree-nonheap-object]
  158 |         _GLIBCXX_OPERATOR_DELETE(_GLIBCXX_SIZED_DEALLOC(__p, __n));
      |                                 ^
In file included from /home/marre55/picongpu/thirdParty/toml11/toml.hpp:40,
                 from /home/marre55/picongpu/include/picongpu/plugins/openPMD/toml.cpp:38:
/home/marre55/picongpu/thirdParty/toml11/toml/parser.hpp: In function 'toml::result<Value, std::__cxx11::basic_string<char> > toml::detail::parse_toml_file(location&) [with Value = toml::basic_value<toml::discard_comments, std::unordered_map, std::vector>]':
/home/marre55/picongpu/thirdParty/toml11/toml/parser.hpp:2127:13: note: declared here
 2127 |     if(auto tab = parse_ml_table<value_type>(loc))
      |             ^~~

```
even though according to latest-dev documentation anything gcc-9+ is supported for cpu

### LINKED ISSUE #4622: CI does not test gcc-12
Our documentation, list gcc-12 as a supported compiler but the CI does not test gcc-12
https://picongpu.readthedocs.io/en/latest/install/dependencies.html

### PR DESCRIPTION
**Pull request by psychocoderHPC**
- remove old thirdparty toml11 because it was not cleanly checked in as git subtree
- add version 3.7.1 `GIT_AUTHOR_NAME="Third Party" GIT_AUTHOR_EMAIL="picongpu@hzdr.de" git subtree add --prefix thirdParty/toml11 git@github.com:ToruNiina/toml11.git v3.7.1 --squash`

fix #4620

### CODE REVIEW

**Comment by BrianMarre** [comment]
@psychocoderHPC you seem to reference the wrong issue, you probably want to refer to #4620

**Comment by psychocoderHPC** [comment]
> @psychocoderHPC you seem to reference the wrong issue, you probably want to refer to #4620

Thanks, I updated the description

**Review by PrometheusPi — CHANGES_REQUESTED** [review]
I am confused @psychocoderHPC. According to the PR description you "remove old thirdparty toml11". But the diff shows `+13,006 −106` changes. 

If these are automatically created, please provide more details how this was done. 
If you wrote them yourself, please provide more details what these 13k new lines do.

**Comment by psychocoderHPC** [comment]
> I am confused @psychocoderHPC. According to the PR description you "remove old thirdparty toml11". But the diff shows `+13,006 −106` changes.
> 
> If these are automatically created, please provide more details how this was done. If you wrote them yourself, please provide more details what these 13k new lines do.

Before @franzpoeschel was only adding some files by hand. This is possible but will throw it away the history.

**Review by PrometheusPi — APPROVED** [review]
The git command was a bit hidden - it's in the main PR message.

**Pull request merged**
