### PR TITLE
C Includes PMacc: Fix Correct C++ Style

### PR DESCRIPTION
**Pull request by ax3l**
Fix all includes in PMacc to use correct [C++ include style](https://en.wikipedia.org/wiki/C%2B%2B_Standard_Library#C_standard_library) instead of C-style.

~~`stdint` is not standard before C++11 and is replaced with `<boost/cstdint.hpp>` instead.~~ (later when switched to C++11, else will change prefix to `boost` for those types)

### CODE REVIEW

**Comment by PrometheusPi** [comment]
@ax3l why did you close this pull request?

**Comment by ax3l** [comment]
wrong button.

**Comment by PrometheusPi** [comment]
My fault - the revert in the second commit resulted in no files changed.

**Comment by ax3l** [comment]
ah no, indeed that was the reason I closed it.

**Pull request closed without merging**
