### PR TITLE
begin kernel names with upper case letter

### PR DESCRIPTION
**Pull request by psychocoderHPC**
- rename kernel which begin with lower case letter
- update kernel call with new name

### CODE REVIEW

**Comment by PrometheusPi** [comment]
@psychocoderHPC In `src/libPMacc/include/particles/IdProvider.hpp` there are still some instances of `setNextId` - line 81 and 92

**Comment by psychocoderHPC** [comment]
`setNextId` in line 81 and 92 are not kernels

**Comment by PrometheusPi** [comment]
In `./src/libPMacc/include/particles/operations/splitIntoListOfFrames.kernel` line 178 you have a function defined as `splitIntoListOfFrames` which you use in `./src/picongpu/include/plugins/hdf5/restart/LoadSpecies.hpp:193` and `./src/picongpu/include/plugins/adios/restart/LoadSpecies.hpp:169`. Do you realy want to use the function there or the kernel? Wky the name conflict?

**Comment by psychocoderHPC** [comment]
The kernel is in it's own namespace, therefore it not conflicts. IN both cases the function should be called. A kernel is called with `PMACC_KERNEL(...)`

@PrometheusPi  Please use links to code parts, this helps to follow the issu.

**Comment by PrometheusPi** [comment]
@psychocoderHPC thanks for checking

**Pull request merged**
