### PR TITLE
Changelog: 0.4.0

### PR DESCRIPTION
**Pull request by ax3l**
Draft for the 0.4.0 changelog, up to PR #2679.

- [x] Title: CPU Support, Particle Filter, Probes & Merging
- [x] Abstract

- add PRs:
  - [x] improved period syntax in restart scripts #2650
  - [x] PMacc event system sync before blocking MPI calls #2683
  - [x] Alpaka 0.3.3 #2684

### CODE REVIEW

**Comment by ax3l** [comment]
@ComputationalRadiationPhysics/picongpu-maintainers please review the proposed changelog. It's open since about a month...

**Comment by ax3l** [comment]
@PrometheusPi just another three PRs added to changelog (see PR description)

**Comment by ax3l** [comment]
yep, present is the best. people just need to write their *PR titles* in present tense and it will show up as such in the changelog :-)

**Comment by ax3l** [comment]
@PrometheusPi @psychocoderHPC ready for merge :)

**Comment by psychocoderHPC** [comment]
can I merge this PR?

**Comment by ax3l** [comment]
yes

**Pull request merged**
