### PR TITLE
Updatet documentation of AOFDTD

### PR DESCRIPTION
**Pull request by jtrojok**
I added the dispersion relation and stability condition for the aofdtd field solver to the documentation.

### CODE REVIEW

**Review by steindev — APPROVED** [review]
Great work! We refactored the original version in an offline session already.

**Comment by psychocoderHPC** [comment]
@steindev Can we bring the stability condition as runtime or compile-time assert into the codebase?

**Comment by sbastrakov** [comment]
Perhaps someone besides those working on this PR should have reviewed it as well.

**Comment by steindev** [comment]
> @steindev Can we bring the stability condition as runtime or compile-time assert into the codebase?

In principle, yes. It is on my list. Just need to test before, whether these conditions really result in stability.

**Comment by steindev** [comment]
> Perhaps someone besides those working on this PR should have reviewed it as well.

As this was just an addition to documentation, I thought will be ok this way :sweat_smile:

**Comment by steindev** [comment]
By the way, we forgot to post results showing that the new stability condition actually does provide the expected limit. Following pictures show 2D  TMz simulations where a unit step Ez field is fed in the simulation center cell. Stable field solve results in a positive Ez field in the domain propagating like cylindrical wave. unstable field solve results in checkerboard like field distribution, see Taflove ch. 4.7.

1. **AOFDTD 1 neighbor (=Yee)** (reference to verify that lowest order solver behaves as expected)
  ξ_max = 0.995 (stable)
  numerical-stability_AOFDTD-1
  
  ξ_max = 1.005 (unstable)
  numerical-stability_AOFDTD-1_unstable

2. **AOFDTD 2 neighbors** Now using the newly derived stability condition to derive the time step
  ξ_max = 0.995 (stable)
  numerical-stability_AOFDTD-2_0 995
  
  ξ_max = 1.005 (unstable)
  numerical-stability_AOFDTD-2_1 005

3. **AOFDTD 8 neighbors** Even smaller time step as determined from new stability condition
  ξ_max = 0.995 (stable)
  numerical-stability_AOFDTD-8_0 995
  
  ξ_max = 1.005 (unstable)
  numerical-stability_AOFDTD-8_1 005

All cases show the expected stable or unstable behavior.
By induction I conclude that the derived stability condition is correct ( :wink: )

However, be aware that choosing a smaller time step than the maximum provided by the stability condition will reduce the numerical error for two or more neighbors (in contrast to Yee's method). See paragraph on numerical dispersion in the manual.

**Pull request merged**
