### PR TITLE
remove unnecessary executable rights

### PR DESCRIPTION
**Pull request by PrometheusPi**
This pull request changes the `rwxr-xr-x` rights of several files to `rw-r--r--`.

### CODE REVIEW

**Comment by PrometheusPi** [comment]
please **do not merge** there are several more wrong file permissions

**Comment by PrometheusPi** [comment]
Side information: The `*.profile.example` files do not need to be executable since they are sourced by the `*.tpl`.

**Comment by ax3l** [comment]
@PrometheusPi nice update, but please keep the profile examples +x for all. Users copy the file and *source it by hand* in their terminal.

**Comment by PrometheusPi** [comment]
@ax3l But for `source some_file`, `some_file` does not need to be executable.

**Comment by ax3l** [comment]
that is very true and avoids wrong usage. I like that.

**Pull request merged**
