### PR TITLE
fix copyright comment

### PR DESCRIPTION
**Pull request by BrianMarre**
fixes the doubled space in our copyright comments

### CODE REVIEW

**Review by psychocoderHPC — DISMISSED** [review]
please commit this change as tools author

**Comment by steindev** [comment]
@BrianMarre please also resolve the merge conflicts before.

**Comment by BrianMarre** [comment]
@psychocoderHPC changed commit author to Tools and fixed merge conflict

**Comment by BrianMarre** [comment]
@psychocoderHPC please review again

**Review by ikbuibui — APPROVED** [review]

**Pull request merged**
