### PR TITLE
README for dev server install scripts

### PR DESCRIPTION
**Pull request by BrianMarre**
adds a short README for the spack dependency install scripts.

### CODE REVIEW

**Comment by BrianMarre** [comment]
@psychocoderHPC please restart the CI, failed after timeout while trying to get the container image.

**Comment by chillenzer** [comment]
First thing to note: You've used `rst` directives in Markdown.

**Comment by BrianMarre** [comment]
@chillenzer Thanks! Did not realize that there was a difference, should be fixed now.

**Review by ikbuibui — APPROVED** [review]
Looks good

**Pull request merged**
