### PR TITLE
MaxwellSolver: Directional Splitting

### PR DESCRIPTION
**Pull request by Heikman**
Current updates on the implementation of the vacuum Maxwell solver for Directional Splitting

### CODE REVIEW

**Comment by ax3l** [comment]
thx!

for this preview: does this branch contain any bug fixes?

I only see updates from #790 and #893 that should be handled there (and this branch can then reduced by a rebase).

**Comment by Heikman** [comment]
I adopted all bugfixes related to #889, #890, #891, #892 manually.

**Comment by ax3l** [comment]
ok but besides that there are no new bugs found (yet) that are still and `dev`?

my goal would be to port each found back in the solver independently to `dev` so I can keep #894 up to date by rebasing on `dev`.

**Comment by psychocoderHPC** [comment]
Please do not adopted bugfixes by hand.
One way is `git cherry-pick` this avoids rebase problems later on.

A second problem is that we lose the original author if you close the original pull without merging and move the code by hand.

**Comment by ax3l** [comment]
just let me highlight this again: giving credit is very important. we use `git` to exactly allow that and to track contributions. pls don't copy & paste patches, `git cherry-pick` and `git rebase` are the right ways to go.

**Comment by bussmann** [comment]
I absolutely, giving credit is important!

**Comment by psychocoderHPC** [comment]
please rebase me

**Comment by ax3l** [comment]
this branch does not contain changes to `dev` anymore

**Pull request closed without merging**
