### PR TITLE
Compatibility to new unified ISAAC naming scheme

### PR DESCRIPTION
**Pull request by FelixTUD**
Updates IsaacPlugin.hpp with the new ISAAC naming standard used in PIConGPU coming with the rework PR ComputationalRadiationPhysics/isaac#132

- reaktivate CI tests for ISAAC
  - keep clang-cuda tests disabled due to compile issues
  
# Todo
- [x] needs ComputationalRadiationPhysics/isaac#132 merged into dev
- [x] CI updated to use ISAAC dev
- [x] merge after #3569
- [x] must be released against #3575

### CODE REVIEW

**Comment by PrometheusPi** [comment]
@psychocoderHPC ComputationalRadiationPhysics/isaac#132 was merges there is only a CI update missing. Are you or @FelixTUD implementing the CI change?

**Comment by psychocoderHPC** [comment]
> @psychocoderHPC [ComputationalRadiationPhysics/isaac#132](https://github.com/ComputationalRadiationPhysics/isaac/pull/132) was merges there is only a CI update missing. Are you or @FelixTUD implementing the CI change?

I have it on the todo list for this week.

**Comment by psychocoderHPC** [comment]
I rebase this PR, compiled a custom ISAAC version (latest dev but with fixed sha)

**Comment by psychocoderHPC** [comment]
It looks like ISAAC is not used for PIConGPU, I will add some more checks to see what's going on.

**Comment by psychocoderHPC** [comment]
> It looks like ISAAC is not used for PIConGPU, I will add some more checks to see what's going on.

#3569 should fix the issue

**Comment by psychocoderHPC** [comment]
PR can now be reviewed and merged.

**Review by sbastrakov — APPROVED** [review]

**Comment by sbastrakov** [comment]
@PrometheusPi do you want to have a look before I click merge? I feel it is not necessary as the changes are technical.

**Comment by psychocoderHPC** [comment]
@sbastrakov could you merge this PR that we have ISAAC in our CI. Maybe @PrometheusPi is on vacation.

**Pull request merged**
