### PR TITLE
hzdr dev server profile

### PR DESCRIPTION
**Pull request by BrianMarre**
upgrades to python 3.9.12 for testing of pypicongpu,

includes spack install commands for future reference

### CODE REVIEW

**Comment by psychocoderHPC** [comment]
@BrianMarre could you please force push to this PR again, the CI needs to be restarted from the first stage, I am not able to trigger it via the web interface :-(
Please rebase your PR against the current dev branch.

**Comment by BrianMarre** [comment]
yes, will do once I have updated the profile to use boost 1.74 as discussed offline

**Comment by BrianMarre** [comment]
Done, but the CI seems to have encountered a different bug this time.

**Comment by BrianMarre** [comment]
@psychocoderHPC is this PR ready?

**Review by sbastrakov — APPROVED** [review]

**Comment by sbastrakov** [comment]
@psychocoderHPC do we need to wait for your review?

**Review by psychocoderHPC — APPROVED** [review]

**Pull request merged**
